
sync_folder_root=ENV['OO_VGRNT_CIRCUITS_SYNC_ROOT'] || "/home/oneops/build"

Vagrant.configure(2) do |config|

  config.vm.box = "oneops"

  # Use the vagrant-cachier plugin, if installed, to cache downloaded packages
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.network "forwarded_port", guest: 3001, host: 3003
  config.vm.network "forwarded_port", guest: 3000, host: 9090
  config.vm.network "forwarded_port", guest: 8080, host: 9091
  config.vm.network "forwarded_port", guest: 8161, host: 8166

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 6144
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
  end

  # configure vagrant to push file from local to remote vm.
  config.push.define "local-exec" do |push|
    push.script = "update_war_file.sh"
  end

  #if you want to sync circuits on your host with vagrant then create an env variable ONEOPS_HOME on your host that points to a directory that houses all the circuits and oneops core
  if !ENV['ONEOPS_HOME'].nil?
    config.vm.synced_folder ENV['ONEOPS_HOME']+"/circuit-oneops-1", "#{sync_folder_root}/circuit-oneops-1",owner: "root",group: "root"
    config.vm.synced_folder ENV['ONEOPS_HOME']+"/oneops/oneops-admin", "#{sync_folder_root}/oneops-admin",owner: "root",group: "root",type: "rsync"

    config.vm.provision "configure_circuits", type: "shell", inline: $script_configure_circuits, env: {"sync_folder_root" => sync_folder_root}
    config.vm.provision "script_configure_circuits_shared", type: "shell", inline: $script_configure_circuits_shared, env: {"sync_folder_root" => sync_folder_root}, run: "always"
    config.vm.provision "use_latest_inductor", type: "shell", inline: $script_use_latest_inductor, env: {"sync_folder_root" => sync_folder_root}
  end
end

$script_configure_circuits = <<SCRIPT
  echo "configuring inductor to use circuits on host"
  cd /opt/oneops/inductor

  echo "deleting/unlinking existing circuits"
  circuits=( circuit-oneops-1 )

  for circuit in "${circuits[@]}"
  do
    if [[ -L "$circuit" && -d "$circuit" ]]
    then
      echo "$circuit is a symlink to a directory. unlinking the symlink"
      sudo unlink $circuit
    else
      echo "$circuit is a directory. deleting it"
      sudo rm -Rf $circuit
    fi
  done

  echo "creating symlinks"
  for circuit in "${circuits[@]}"
  do
    sudo ln -s "$sync_folder_root/$circuit/" $circuit
  done
  echo "script completed successfully"
SCRIPT

$script_configure_circuits_shared = <<SCRIPT
  echo "configureing oneops admin shared"
  cp -RT $sync_folder_root/circuit-oneops-1/shared /opt/oneops/inductor/shared
  cp -RT $sync_folder_root/circuit-oneops-1/shared /home/oneops/build/oneops-admin/lib/shared
  cp -RT $sync_folder_root/circuit-oneops-1/shared /usr/local/share/gems/gems/oneops-admin-adapter-1.0.0/lib/shared
  echo "script completed successfully"
SCRIPT

$script_use_latest_inductor = <<SCRIPT
  inductor_file_path=$(gem which inductor)
  lib_dir=$(dirname $inductor_file_path)
  oneops_admin_path=$(dirname $lib_dir)

  cd $oneops_admin_path

  echo "removing inductor jar from $oneops_admin_path/target"
  rm target/inductor-*.jar

  echo "copying latest inductor jar from $sync_folder_root/oneops-admin/target to $oneops_admin_path/target"
  cp "$sync_folder_root/oneops-admin/target"/inductor-*.jar target/
SCRIPT
