tools:
  jdk: 8
  maven: 3.5.0

triggers:
  - manual: Run default
flows:
  default:
    - call: versionsCheck
    - call: pr
  pr:
    try:
    - echo "Running build for $GITHUB_PR_URL"
    - call: versionsCheck
    - (name Maven Wrapper Build) ./mvnw clean package -pl adapter,amq-plugin,antenna,cms-admin,cmsdal,controller,daq,display,inductor,oo-commons,opamp,search,sensor,transistor,transmitter,batch,oneops-admin,db-schema,oneops-model,crawler 
    - slack.postMessage:
        message: " Looper build $BUILD_URL  is successful "
        channelId: 'oneops_team'
    catch:
    - slack.postMessage:
        message: " Looper build $BUILD_URL  has failed. Please check the looper build. "
        channelId: 'oneops_team'
        
  versionsCheck:
    - (name JDK Version) java -version
    - (name Maven version) mvn -v
