tools:
  jdk: 8
  maven: 3.5.0
flows:
  default:
    - sudo yum -y install gcc mysql-devel ruby-devel rubygems
    #- gem install bundle
    #- ./mvnw install
    #- ./mvnw --batch-mode release:prepare
    
    - shell: mvn clean install
  pr:
    call: default
