tools:
  jdk: 8
  maven: 3.5.0
flows:
  default:
    #- sudo yum -y install gcc mysql-devel ruby-devel rubygems
    - gem install bundle
    - gem install mysql-devel
    - gem install ruby-devel
    - gem install rubygems
    - bundle show | grep ruby
    - bundle show | grep ruby
  
    #- ./mvnw install
    #- ./mvnw --batch-mode release:prepare
    
    - shell: mvn clean install
  pr:
    call: default
