/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables;


import com.oneops.crawler.jooq.cms.Indexes;
import com.oneops.crawler.jooq.cms.Keys;
import com.oneops.crawler.jooq.cms.Kloopzcm;
import com.oneops.crawler.jooq.cms.tables.records.CmCiAttributesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmCiAttributes extends TableImpl<CmCiAttributesRecord> {

    private static final long serialVersionUID = 1017540508;

    /**
     * The reference instance of <code>kloopzcm.cm_ci_attributes</code>
     */
    public static final CmCiAttributes CM_CI_ATTRIBUTES = new CmCiAttributes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CmCiAttributesRecord> getRecordType() {
        return CmCiAttributesRecord.class;
    }

    /**
     * The column <code>kloopzcm.cm_ci_attributes.ci_attribute_id</code>.
     */
    public final TableField<CmCiAttributesRecord, Long> CI_ATTRIBUTE_ID = createField("ci_attribute_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cm_ci_attributes.ci_id</code>.
     */
    public final TableField<CmCiAttributesRecord, Long> CI_ID = createField("ci_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cm_ci_attributes.attribute_id</code>.
     */
    public final TableField<CmCiAttributesRecord, Integer> ATTRIBUTE_ID = createField("attribute_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cm_ci_attributes.df_attribute_value</code>.
     */
    public final TableField<CmCiAttributesRecord, String> DF_ATTRIBUTE_VALUE = createField("df_attribute_value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>kloopzcm.cm_ci_attributes.dj_attribute_value</code>.
     */
    public final TableField<CmCiAttributesRecord, String> DJ_ATTRIBUTE_VALUE = createField("dj_attribute_value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>kloopzcm.cm_ci_attributes.owner</code>.
     */
    public final TableField<CmCiAttributesRecord, String> OWNER = createField("owner", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>kloopzcm.cm_ci_attributes.comments</code>.
     */
    public final TableField<CmCiAttributesRecord, String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>kloopzcm.cm_ci_attributes.created</code>.
     */
    public final TableField<CmCiAttributesRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>kloopzcm.cm_ci_attributes.updated</code>.
     */
    public final TableField<CmCiAttributesRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>kloopzcm.cm_ci_attributes</code> table reference
     */
    public CmCiAttributes() {
        this(DSL.name("cm_ci_attributes"), null);
    }

    /**
     * Create an aliased <code>kloopzcm.cm_ci_attributes</code> table reference
     */
    public CmCiAttributes(String alias) {
        this(DSL.name(alias), CM_CI_ATTRIBUTES);
    }

    /**
     * Create an aliased <code>kloopzcm.cm_ci_attributes</code> table reference
     */
    public CmCiAttributes(Name alias) {
        this(alias, CM_CI_ATTRIBUTES);
    }

    private CmCiAttributes(Name alias, Table<CmCiAttributesRecord> aliased) {
        this(alias, aliased, null);
    }

    private CmCiAttributes(Name alias, Table<CmCiAttributesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kloopzcm.KLOOPZCM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CM_CI_ATTRIBUTES_ATTR_IDX, Indexes.CM_CI_ATTRIBUTES_CI_IDX, Indexes.CM_CI_ATTRIBUTES_PK, Indexes.CM_CI_ATTRIBUTES_UNIQ_ATTRID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CmCiAttributesRecord> getPrimaryKey() {
        return Keys.CM_CI_ATTRIBUTES_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CmCiAttributesRecord>> getKeys() {
        return Arrays.<UniqueKey<CmCiAttributesRecord>>asList(Keys.CM_CI_ATTRIBUTES_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CmCiAttributesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CmCiAttributesRecord, ?>>asList(Keys.CM_CI_ATTRIBUTES__CM_CI_ATTRIBUTES_CIID_FK, Keys.CM_CI_ATTRIBUTES__CM_CI_ATTRIBUTES_ATTR_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiAttributes as(String alias) {
        return new CmCiAttributes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiAttributes as(Name alias) {
        return new CmCiAttributes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CmCiAttributes rename(String name) {
        return new CmCiAttributes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CmCiAttributes rename(Name name) {
        return new CmCiAttributes(name, null);
    }
}
