/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables;


import com.oneops.crawler.jooq.cms.Indexes;
import com.oneops.crawler.jooq.cms.Keys;
import com.oneops.crawler.jooq.cms.Kloopzcm;
import com.oneops.crawler.jooq.cms.tables.records.CmCiRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmCi extends TableImpl<CmCiRecord> {

    private static final long serialVersionUID = 237042409;

    /**
     * The reference instance of <code>kloopzcm.cm_ci</code>
     */
    public static final CmCi CM_CI = new CmCi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CmCiRecord> getRecordType() {
        return CmCiRecord.class;
    }

    /**
     * The column <code>kloopzcm.cm_ci.ci_id</code>.
     */
    public final TableField<CmCiRecord, Long> CI_ID = createField("ci_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.ns_id</code>.
     */
    public final TableField<CmCiRecord, Long> NS_ID = createField("ns_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.class_id</code>.
     */
    public final TableField<CmCiRecord, Integer> CLASS_ID = createField("class_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.ci_name</code>.
     */
    public final TableField<CmCiRecord, String> CI_NAME = createField("ci_name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.ci_goid</code>.
     */
    public final TableField<CmCiRecord, String> CI_GOID = createField("ci_goid", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.comments</code>.
     */
    public final TableField<CmCiRecord, String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.ci_state_id</code>.
     */
    public final TableField<CmCiRecord, Integer> CI_STATE_ID = createField("ci_state_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.last_applied_rfc_id</code>.
     */
    public final TableField<CmCiRecord, Long> LAST_APPLIED_RFC_ID = createField("last_applied_rfc_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>kloopzcm.cm_ci.created_by</code>.
     */
    public final TableField<CmCiRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.updated_by</code>.
     */
    public final TableField<CmCiRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.created</code>.
     */
    public final TableField<CmCiRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>kloopzcm.cm_ci.updated</code>.
     */
    public final TableField<CmCiRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>kloopzcm.cm_ci</code> table reference
     */
    public CmCi() {
        this(DSL.name("cm_ci"), null);
    }

    /**
     * Create an aliased <code>kloopzcm.cm_ci</code> table reference
     */
    public CmCi(String alias) {
        this(DSL.name(alias), CM_CI);
    }

    /**
     * Create an aliased <code>kloopzcm.cm_ci</code> table reference
     */
    public CmCi(Name alias) {
        this(alias, CM_CI);
    }

    private CmCi(Name alias, Table<CmCiRecord> aliased) {
        this(alias, aliased, null);
    }

    private CmCi(Name alias, Table<CmCiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kloopzcm.KLOOPZCM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CM_CI_3COLS_IDX, Indexes.CM_CI_CL_IDX, Indexes.CM_CI_NS_IDX, Indexes.CM_CI_PK, Indexes.DF_CI_GOID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CmCiRecord> getPrimaryKey() {
        return Keys.CM_CI_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CmCiRecord>> getKeys() {
        return Arrays.<UniqueKey<CmCiRecord>>asList(Keys.CM_CI_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CmCiRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CmCiRecord, ?>>asList(Keys.CM_CI__CM_CI_NS_FK, Keys.CM_CI__CM_CI_CLID_FK, Keys.CM_CI__CM_CI_STID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCi as(String alias) {
        return new CmCi(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCi as(Name alias) {
        return new CmCi(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CmCi rename(String name) {
        return new CmCi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CmCi rename(Name name) {
        return new CmCi(name, null);
    }
}
