/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables;


import com.oneops.crawler.jooq.cms.Indexes;
import com.oneops.crawler.jooq.cms.Keys;
import com.oneops.crawler.jooq.cms.Kloopzcm;
import com.oneops.crawler.jooq.cms.tables.records.CmsEventTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsEventType extends TableImpl<CmsEventTypeRecord> {

    private static final long serialVersionUID = 699032139;

    /**
     * The reference instance of <code>kloopzcm.cms_event_type</code>
     */
    public static final CmsEventType CMS_EVENT_TYPE = new CmsEventType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CmsEventTypeRecord> getRecordType() {
        return CmsEventTypeRecord.class;
    }

    /**
     * The column <code>kloopzcm.cms_event_type.event_type_id</code>.
     */
    public final TableField<CmsEventTypeRecord, Integer> EVENT_TYPE_ID = createField("event_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.cms_event_type.event_type</code>.
     */
    public final TableField<CmsEventTypeRecord, String> EVENT_TYPE = createField("event_type", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * Create a <code>kloopzcm.cms_event_type</code> table reference
     */
    public CmsEventType() {
        this(DSL.name("cms_event_type"), null);
    }

    /**
     * Create an aliased <code>kloopzcm.cms_event_type</code> table reference
     */
    public CmsEventType(String alias) {
        this(DSL.name(alias), CMS_EVENT_TYPE);
    }

    /**
     * Create an aliased <code>kloopzcm.cms_event_type</code> table reference
     */
    public CmsEventType(Name alias) {
        this(alias, CMS_EVENT_TYPE);
    }

    private CmsEventType(Name alias, Table<CmsEventTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private CmsEventType(Name alias, Table<CmsEventTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kloopzcm.KLOOPZCM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CMS_EVENT_TYPE_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CmsEventTypeRecord> getPrimaryKey() {
        return Keys.CMS_EVENT_TYPE_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CmsEventTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<CmsEventTypeRecord>>asList(Keys.CMS_EVENT_TYPE_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsEventType as(String alias) {
        return new CmsEventType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsEventType as(Name alias) {
        return new CmsEventType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CmsEventType rename(String name) {
        return new CmsEventType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CmsEventType rename(Name name) {
        return new CmsEventType(name, null);
    }
}
