/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables;


import com.oneops.crawler.jooq.cms.Indexes;
import com.oneops.crawler.jooq.cms.Keys;
import com.oneops.crawler.jooq.cms.Kloopzcm;
import com.oneops.crawler.jooq.cms.tables.records.DjApprovalStatesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjApprovalStates extends TableImpl<DjApprovalStatesRecord> {

    private static final long serialVersionUID = 69597947;

    /**
     * The reference instance of <code>kloopzcm.dj_approval_states</code>
     */
    public static final DjApprovalStates DJ_APPROVAL_STATES = new DjApprovalStates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DjApprovalStatesRecord> getRecordType() {
        return DjApprovalStatesRecord.class;
    }

    /**
     * The column <code>kloopzcm.dj_approval_states.state_id</code>.
     */
    public final TableField<DjApprovalStatesRecord, Integer> STATE_ID = createField("state_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.dj_approval_states.state_name</code>.
     */
    public final TableField<DjApprovalStatesRecord, String> STATE_NAME = createField("state_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * Create a <code>kloopzcm.dj_approval_states</code> table reference
     */
    public DjApprovalStates() {
        this(DSL.name("dj_approval_states"), null);
    }

    /**
     * Create an aliased <code>kloopzcm.dj_approval_states</code> table reference
     */
    public DjApprovalStates(String alias) {
        this(DSL.name(alias), DJ_APPROVAL_STATES);
    }

    /**
     * Create an aliased <code>kloopzcm.dj_approval_states</code> table reference
     */
    public DjApprovalStates(Name alias) {
        this(alias, DJ_APPROVAL_STATES);
    }

    private DjApprovalStates(Name alias, Table<DjApprovalStatesRecord> aliased) {
        this(alias, aliased, null);
    }

    private DjApprovalStates(Name alias, Table<DjApprovalStatesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kloopzcm.KLOOPZCM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DJ_APPROVAL_STATES_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DjApprovalStatesRecord> getPrimaryKey() {
        return Keys.DJ_APPROVAL_STATES_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DjApprovalStatesRecord>> getKeys() {
        return Arrays.<UniqueKey<DjApprovalStatesRecord>>asList(Keys.DJ_APPROVAL_STATES_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjApprovalStates as(String alias) {
        return new DjApprovalStates(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjApprovalStates as(Name alias) {
        return new DjApprovalStates(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DjApprovalStates rename(String name) {
        return new DjApprovalStates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DjApprovalStates rename(Name name) {
        return new DjApprovalStates(name, null);
    }
}
