/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables;


import com.oneops.crawler.jooq.cms.Indexes;
import com.oneops.crawler.jooq.cms.Keys;
import com.oneops.crawler.jooq.cms.Kloopzcm;
import com.oneops.crawler.jooq.cms.tables.records.DjDpmtApprovalsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjDpmtApprovals extends TableImpl<DjDpmtApprovalsRecord> {

    private static final long serialVersionUID = 915349894;

    /**
     * The reference instance of <code>kloopzcm.dj_dpmt_approvals</code>
     */
    public static final DjDpmtApprovals DJ_DPMT_APPROVALS = new DjDpmtApprovals();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DjDpmtApprovalsRecord> getRecordType() {
        return DjDpmtApprovalsRecord.class;
    }

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.approval_id</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, Long> APPROVAL_ID = createField("approval_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.deployment_id</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, Long> DEPLOYMENT_ID = createField("deployment_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.govern_ci_id</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, Long> GOVERN_CI_ID = createField("govern_ci_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.govern_ci</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, String> GOVERN_CI = createField("govern_ci", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.state_id</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, Integer> STATE_ID = createField("state_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.updated_by</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.created</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.updated</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.expires_in</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, Integer> EXPIRES_IN = createField("expires_in", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>kloopzcm.dj_dpmt_approvals.comments</code>.
     */
    public final TableField<DjDpmtApprovalsRecord, String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>kloopzcm.dj_dpmt_approvals</code> table reference
     */
    public DjDpmtApprovals() {
        this(DSL.name("dj_dpmt_approvals"), null);
    }

    /**
     * Create an aliased <code>kloopzcm.dj_dpmt_approvals</code> table reference
     */
    public DjDpmtApprovals(String alias) {
        this(DSL.name(alias), DJ_DPMT_APPROVALS);
    }

    /**
     * Create an aliased <code>kloopzcm.dj_dpmt_approvals</code> table reference
     */
    public DjDpmtApprovals(Name alias) {
        this(alias, DJ_DPMT_APPROVALS);
    }

    private DjDpmtApprovals(Name alias, Table<DjDpmtApprovalsRecord> aliased) {
        this(alias, aliased, null);
    }

    private DjDpmtApprovals(Name alias, Table<DjDpmtApprovalsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kloopzcm.KLOOPZCM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DJ_DPMT_APPROVALS_CID_IDX, Indexes.DJ_DPMT_APPROVALS_DPMT_IDX, Indexes.DJ_DPMT_APPROVALS_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DjDpmtApprovalsRecord> getPrimaryKey() {
        return Keys.DJ_DPMT_APPROVALS_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DjDpmtApprovalsRecord>> getKeys() {
        return Arrays.<UniqueKey<DjDpmtApprovalsRecord>>asList(Keys.DJ_DPMT_APPROVALS_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DjDpmtApprovalsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DjDpmtApprovalsRecord, ?>>asList(Keys.DJ_DPMT_APPROVALS__DJ_DPMT_APPROVALS_DPMT_ID_FK, Keys.DJ_DPMT_APPROVALS__DJ_DPMT_APPROVALS_STATES_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovals as(String alias) {
        return new DjDpmtApprovals(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovals as(Name alias) {
        return new DjDpmtApprovals(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DjDpmtApprovals rename(String name) {
        return new DjDpmtApprovals(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DjDpmtApprovals rename(Name name) {
        return new DjDpmtApprovals(name, null);
    }
}
