/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables;


import com.oneops.crawler.jooq.cms.Indexes;
import com.oneops.crawler.jooq.cms.Keys;
import com.oneops.crawler.jooq.cms.Kloopzcm;
import com.oneops.crawler.jooq.cms.tables.records.DjRfcCiAttributesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjRfcCiAttributes extends TableImpl<DjRfcCiAttributesRecord> {

    private static final long serialVersionUID = 468742953;

    /**
     * The reference instance of <code>kloopzcm.dj_rfc_ci_attributes</code>
     */
    public static final DjRfcCiAttributes DJ_RFC_CI_ATTRIBUTES = new DjRfcCiAttributes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DjRfcCiAttributesRecord> getRecordType() {
        return DjRfcCiAttributesRecord.class;
    }

    /**
     * The column <code>kloopzcm.dj_rfc_ci_attributes.rfc_attr_id</code>.
     */
    public final TableField<DjRfcCiAttributesRecord, Long> RFC_ATTR_ID = createField("rfc_attr_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.dj_rfc_ci_attributes.rfc_id</code>.
     */
    public final TableField<DjRfcCiAttributesRecord, Long> RFC_ID = createField("rfc_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.dj_rfc_ci_attributes.attribute_id</code>.
     */
    public final TableField<DjRfcCiAttributesRecord, Integer> ATTRIBUTE_ID = createField("attribute_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.dj_rfc_ci_attributes.old_attribute_value</code>.
     */
    public final TableField<DjRfcCiAttributesRecord, String> OLD_ATTRIBUTE_VALUE = createField("old_attribute_value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>kloopzcm.dj_rfc_ci_attributes.new_attribute_value</code>.
     */
    public final TableField<DjRfcCiAttributesRecord, String> NEW_ATTRIBUTE_VALUE = createField("new_attribute_value", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.dj_rfc_ci_attributes.owner</code>.
     */
    public final TableField<DjRfcCiAttributesRecord, String> OWNER = createField("owner", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>kloopzcm.dj_rfc_ci_attributes.comments</code>.
     */
    public final TableField<DjRfcCiAttributesRecord, String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>kloopzcm.dj_rfc_ci_attributes.created</code>.
     */
    public final TableField<DjRfcCiAttributesRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>kloopzcm.dj_rfc_ci_attributes</code> table reference
     */
    public DjRfcCiAttributes() {
        this(DSL.name("dj_rfc_ci_attributes"), null);
    }

    /**
     * Create an aliased <code>kloopzcm.dj_rfc_ci_attributes</code> table reference
     */
    public DjRfcCiAttributes(String alias) {
        this(DSL.name(alias), DJ_RFC_CI_ATTRIBUTES);
    }

    /**
     * Create an aliased <code>kloopzcm.dj_rfc_ci_attributes</code> table reference
     */
    public DjRfcCiAttributes(Name alias) {
        this(alias, DJ_RFC_CI_ATTRIBUTES);
    }

    private DjRfcCiAttributes(Name alias, Table<DjRfcCiAttributesRecord> aliased) {
        this(alias, aliased, null);
    }

    private DjRfcCiAttributes(Name alias, Table<DjRfcCiAttributesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kloopzcm.KLOOPZCM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DJ_RFC_CI_ATTR_A_IDX, Indexes.DJ_RFC_CI_ATTR_RFC_IDX, Indexes.DJ_RFC_CI_ATTRIBUTES_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DjRfcCiAttributesRecord> getPrimaryKey() {
        return Keys.DJ_RFC_CI_ATTRIBUTES_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DjRfcCiAttributesRecord>> getKeys() {
        return Arrays.<UniqueKey<DjRfcCiAttributesRecord>>asList(Keys.DJ_RFC_CI_ATTRIBUTES_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DjRfcCiAttributesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DjRfcCiAttributesRecord, ?>>asList(Keys.DJ_RFC_CI_ATTRIBUTES__DJ_RFC_CI_ATTRIBUTES_CIID_FK, Keys.DJ_RFC_CI_ATTRIBUTES__DJ_RFC_CI_ATTRIBUTES_ATRID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiAttributes as(String alias) {
        return new DjRfcCiAttributes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiAttributes as(Name alias) {
        return new DjRfcCiAttributes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DjRfcCiAttributes rename(String name) {
        return new DjRfcCiAttributes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DjRfcCiAttributes rename(Name name) {
        return new DjRfcCiAttributes(name, null);
    }
}
