/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables;


import com.oneops.crawler.jooq.cms.Indexes;
import com.oneops.crawler.jooq.cms.Keys;
import com.oneops.crawler.jooq.cms.Kloopzcm;
import com.oneops.crawler.jooq.cms.tables.records.MdRelationAttributesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdRelationAttributes extends TableImpl<MdRelationAttributesRecord> {

    private static final long serialVersionUID = -371381469;

    /**
     * The reference instance of <code>kloopzcm.md_relation_attributes</code>
     */
    public static final MdRelationAttributes MD_RELATION_ATTRIBUTES = new MdRelationAttributes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MdRelationAttributesRecord> getRecordType() {
        return MdRelationAttributesRecord.class;
    }

    /**
     * The column <code>kloopzcm.md_relation_attributes.attribute_id</code>.
     */
    public final TableField<MdRelationAttributesRecord, Integer> ATTRIBUTE_ID = createField("attribute_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.relation_id</code>.
     */
    public final TableField<MdRelationAttributesRecord, Integer> RELATION_ID = createField("relation_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.attribute_name</code>.
     */
    public final TableField<MdRelationAttributesRecord, String> ATTRIBUTE_NAME = createField("attribute_name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.data_type</code>.
     */
    public final TableField<MdRelationAttributesRecord, String> DATA_TYPE = createField("data_type", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.is_mandatory</code>.
     */
    public final TableField<MdRelationAttributesRecord, Boolean> IS_MANDATORY = createField("is_mandatory", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.is_encrypted</code>.
     */
    public final TableField<MdRelationAttributesRecord, Boolean> IS_ENCRYPTED = createField("is_encrypted", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.default_value</code>.
     */
    public final TableField<MdRelationAttributesRecord, String> DEFAULT_VALUE = createField("default_value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.value_format</code>.
     */
    public final TableField<MdRelationAttributesRecord, String> VALUE_FORMAT = createField("value_format", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.description</code>.
     */
    public final TableField<MdRelationAttributesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.created</code>.
     */
    public final TableField<MdRelationAttributesRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>kloopzcm.md_relation_attributes.updated</code>.
     */
    public final TableField<MdRelationAttributesRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>kloopzcm.md_relation_attributes</code> table reference
     */
    public MdRelationAttributes() {
        this(DSL.name("md_relation_attributes"), null);
    }

    /**
     * Create an aliased <code>kloopzcm.md_relation_attributes</code> table reference
     */
    public MdRelationAttributes(String alias) {
        this(DSL.name(alias), MD_RELATION_ATTRIBUTES);
    }

    /**
     * Create an aliased <code>kloopzcm.md_relation_attributes</code> table reference
     */
    public MdRelationAttributes(Name alias) {
        this(alias, MD_RELATION_ATTRIBUTES);
    }

    private MdRelationAttributes(Name alias, Table<MdRelationAttributesRecord> aliased) {
        this(alias, aliased, null);
    }

    private MdRelationAttributes(Name alias, Table<MdRelationAttributesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Kloopzcm.KLOOPZCM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MD_RELATION_ATTRIBUTES_PK, Indexes.MD_RELATION_ATTRIBUTES_R_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MdRelationAttributesRecord> getPrimaryKey() {
        return Keys.MD_RELATION_ATTRIBUTES_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MdRelationAttributesRecord>> getKeys() {
        return Arrays.<UniqueKey<MdRelationAttributesRecord>>asList(Keys.MD_RELATION_ATTRIBUTES_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MdRelationAttributesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MdRelationAttributesRecord, ?>>asList(Keys.MD_RELATION_ATTRIBUTES__MD_RELATION_ATTRIBUTES_MDRID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdRelationAttributes as(String alias) {
        return new MdRelationAttributes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdRelationAttributes as(Name alias) {
        return new MdRelationAttributes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MdRelationAttributes rename(String name) {
        return new MdRelationAttributes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MdRelationAttributes rename(Name name) {
        return new MdRelationAttributes(name, null);
    }
}
