--oneops accounts
CREATE ROLE kloopz LOGIN
  ENCRYPTED PASSWORD 'md5f213e95a1ff83ef692fda9aa87199981'
  NOSUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

CREATE DATABASE kloopzapp
  WITH OWNER = kloopz
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       CONNECTION LIMIT = 1000;
       
--oneops cms
CREATE ROLE kloopzcm LOGIN
  ENCRYPTED PASSWORD 'md5bd21eadfdda4b653e92100ab7cf341d2'
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

CREATE DATABASE kloopzdb
  WITH OWNER = kloopzcm
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       CONNECTION LIMIT = 1000;  

--activiti schema
CREATE ROLE activiti LOGIN
  ENCRYPTED PASSWORD 'md529396e43ae92947c301a806c535bb7b9'
  NOSUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

CREATE DATABASE activitidb
  WITH OWNER = activiti
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       CONNECTION LIMIT = 1000;


  
  