/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmCreateRelation1 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -494003014;

    /**
     * The parameter <code>kloopzcm.cm_create_relation.p_ci_relation_id</code>.
     */
    public static final Parameter<Long> P_CI_RELATION_ID = createParameter("p_ci_relation_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_relation.p_ns_id</code>.
     */
    public static final Parameter<Long> P_NS_ID = createParameter("p_ns_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_relation.p_from_ci_id</code>.
     */
    public static final Parameter<Long> P_FROM_CI_ID = createParameter("p_from_ci_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_relation.p_relation_id</code>.
     */
    public static final Parameter<Integer> P_RELATION_ID = createParameter("p_relation_id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_relation.p_to_ci_id</code>.
     */
    public static final Parameter<Long> P_TO_CI_ID = createParameter("p_to_ci_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_relation.p_rel_goid</code>.
     */
    public static final Parameter<String> P_REL_GOID = createParameter("p_rel_goid", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_relation.p_comments</code>.
     */
    public static final Parameter<String> P_COMMENTS = createParameter("p_comments", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_relation.p_state_id</code>.
     */
    public static final Parameter<Integer> P_STATE_ID = createParameter("p_state_id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public CmCreateRelation1() {
        super("cm_create_relation", Kloopzcm.KLOOPZCM);

        addInParameter(P_CI_RELATION_ID);
        addInParameter(P_NS_ID);
        addInParameter(P_FROM_CI_ID);
        addInParameter(P_RELATION_ID);
        addInParameter(P_TO_CI_ID);
        addInParameter(P_REL_GOID);
        addInParameter(P_COMMENTS);
        addInParameter(P_STATE_ID);
        setOverloaded(true);
    }

    /**
     * Set the <code>p_ci_relation_id</code> parameter IN value to the routine
     */
    public void setPCiRelationId(Long value) {
        setValue(P_CI_RELATION_ID, value);
    }

    /**
     * Set the <code>p_ns_id</code> parameter IN value to the routine
     */
    public void setPNsId(Long value) {
        setValue(P_NS_ID, value);
    }

    /**
     * Set the <code>p_from_ci_id</code> parameter IN value to the routine
     */
    public void setPFromCiId(Long value) {
        setValue(P_FROM_CI_ID, value);
    }

    /**
     * Set the <code>p_relation_id</code> parameter IN value to the routine
     */
    public void setPRelationId(Integer value) {
        setValue(P_RELATION_ID, value);
    }

    /**
     * Set the <code>p_to_ci_id</code> parameter IN value to the routine
     */
    public void setPToCiId(Long value) {
        setValue(P_TO_CI_ID, value);
    }

    /**
     * Set the <code>p_rel_goid</code> parameter IN value to the routine
     */
    public void setPRelGoid(String value) {
        setValue(P_REL_GOID, value);
    }

    /**
     * Set the <code>p_comments</code> parameter IN value to the routine
     */
    public void setPComments(String value) {
        setValue(P_COMMENTS, value);
    }

    /**
     * Set the <code>p_state_id</code> parameter IN value to the routine
     */
    public void setPStateId(Integer value) {
        setValue(P_STATE_ID, value);
    }
}
