/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmCreateCi2 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 2019944711;

    /**
     * The parameter <code>kloopzcm.cm_create_ci.p_ci_id</code>.
     */
    public static final Parameter<Long> P_CI_ID = createParameter("p_ci_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ci.p_ns_id</code>.
     */
    public static final Parameter<Long> P_NS_ID = createParameter("p_ns_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ci.p_class_id</code>.
     */
    public static final Parameter<Integer> P_CLASS_ID = createParameter("p_class_id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ci.p_goid</code>.
     */
    public static final Parameter<String> P_GOID = createParameter("p_goid", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ci.p_ci_name</code>.
     */
    public static final Parameter<String> P_CI_NAME = createParameter("p_ci_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ci.p_comments</code>.
     */
    public static final Parameter<String> P_COMMENTS = createParameter("p_comments", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ci.p_state_id</code>.
     */
    public static final Parameter<Integer> P_STATE_ID = createParameter("p_state_id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ci.p_last_rfc_id</code>.
     */
    public static final Parameter<Long> P_LAST_RFC_ID = createParameter("p_last_rfc_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ci.p_created_by</code>.
     */
    public static final Parameter<String> P_CREATED_BY = createParameter("p_created_by", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public CmCreateCi2() {
        super("cm_create_ci", Kloopzcm.KLOOPZCM);

        addInParameter(P_CI_ID);
        addInParameter(P_NS_ID);
        addInParameter(P_CLASS_ID);
        addInParameter(P_GOID);
        addInParameter(P_CI_NAME);
        addInParameter(P_COMMENTS);
        addInParameter(P_STATE_ID);
        addInParameter(P_LAST_RFC_ID);
        addInParameter(P_CREATED_BY);
        setOverloaded(true);
    }

    /**
     * Set the <code>p_ci_id</code> parameter IN value to the routine
     */
    public void setPCiId(Long value) {
        setValue(P_CI_ID, value);
    }

    /**
     * Set the <code>p_ns_id</code> parameter IN value to the routine
     */
    public void setPNsId(Long value) {
        setValue(P_NS_ID, value);
    }

    /**
     * Set the <code>p_class_id</code> parameter IN value to the routine
     */
    public void setPClassId(Integer value) {
        setValue(P_CLASS_ID, value);
    }

    /**
     * Set the <code>p_goid</code> parameter IN value to the routine
     */
    public void setPGoid(String value) {
        setValue(P_GOID, value);
    }

    /**
     * Set the <code>p_ci_name</code> parameter IN value to the routine
     */
    public void setPCiName(String value) {
        setValue(P_CI_NAME, value);
    }

    /**
     * Set the <code>p_comments</code> parameter IN value to the routine
     */
    public void setPComments(String value) {
        setValue(P_COMMENTS, value);
    }

    /**
     * Set the <code>p_state_id</code> parameter IN value to the routine
     */
    public void setPStateId(Integer value) {
        setValue(P_STATE_ID, value);
    }

    /**
     * Set the <code>p_last_rfc_id</code> parameter IN value to the routine
     */
    public void setPLastRfcId(Long value) {
        setValue(P_LAST_RFC_ID, value);
    }

    /**
     * Set the <code>p_created_by</code> parameter IN value to the routine
     */
    public void setPCreatedBy(String value) {
        setValue(P_CREATED_BY, value);
    }
}
