/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmCreateOpsProcedure extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1835653058;

    /**
     * The parameter <code>kloopzcm.cm_create_ops_procedure.p_procedure_id</code>.
     */
    public static final Parameter<Long> P_PROCEDURE_ID = createParameter("p_procedure_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ops_procedure.p_procedure_name</code>.
     */
    public static final Parameter<String> P_PROCEDURE_NAME = createParameter("p_procedure_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ops_procedure.p_ci_id</code>.
     */
    public static final Parameter<Long> P_CI_ID = createParameter("p_ci_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ops_procedure.p_state_name</code>.
     */
    public static final Parameter<String> P_STATE_NAME = createParameter("p_state_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ops_procedure.p_arglist</code>.
     */
    public static final Parameter<String> P_ARGLIST = createParameter("p_arglist", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ops_procedure.p_created_by</code>.
     */
    public static final Parameter<String> P_CREATED_BY = createParameter("p_created_by", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ops_procedure.p_definition</code>.
     */
    public static final Parameter<String> P_DEFINITION = createParameter("p_definition", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>kloopzcm.cm_create_ops_procedure.p_proc_ci_id</code>.
     */
    public static final Parameter<Long> P_PROC_CI_ID = createParameter("p_proc_ci_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public CmCreateOpsProcedure() {
        super("cm_create_ops_procedure", Kloopzcm.KLOOPZCM);

        addInParameter(P_PROCEDURE_ID);
        addInParameter(P_PROCEDURE_NAME);
        addInParameter(P_CI_ID);
        addInParameter(P_STATE_NAME);
        addInParameter(P_ARGLIST);
        addInParameter(P_CREATED_BY);
        addInParameter(P_DEFINITION);
        addInParameter(P_PROC_CI_ID);
    }

    /**
     * Set the <code>p_procedure_id</code> parameter IN value to the routine
     */
    public void setPProcedureId(Long value) {
        setValue(P_PROCEDURE_ID, value);
    }

    /**
     * Set the <code>p_procedure_name</code> parameter IN value to the routine
     */
    public void setPProcedureName(String value) {
        setValue(P_PROCEDURE_NAME, value);
    }

    /**
     * Set the <code>p_ci_id</code> parameter IN value to the routine
     */
    public void setPCiId(Long value) {
        setValue(P_CI_ID, value);
    }

    /**
     * Set the <code>p_state_name</code> parameter IN value to the routine
     */
    public void setPStateName(String value) {
        setValue(P_STATE_NAME, value);
    }

    /**
     * Set the <code>p_arglist</code> parameter IN value to the routine
     */
    public void setPArglist(String value) {
        setValue(P_ARGLIST, value);
    }

    /**
     * Set the <code>p_created_by</code> parameter IN value to the routine
     */
    public void setPCreatedBy(String value) {
        setValue(P_CREATED_BY, value);
    }

    /**
     * Set the <code>p_definition</code> parameter IN value to the routine
     */
    public void setPDefinition(String value) {
        setValue(P_DEFINITION, value);
    }

    /**
     * Set the <code>p_proc_ci_id</code> parameter IN value to the routine
     */
    public void setPProcCiId(Long value) {
        setValue(P_PROC_CI_ID, value);
    }
}
