/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmDeleteRelation extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1452701194;

    /**
     * The parameter <code>kloopzcm.cm_delete_relation.p_ci_relation_id</code>.
     */
    public static final Parameter<Long> P_CI_RELATION_ID = createParameter("p_ci_relation_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_delete_relation.p_delete4real</code>.
     */
    public static final Parameter<Boolean> P_DELETE4REAL = createParameter("p_delete4real", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public CmDeleteRelation() {
        super("cm_delete_relation", Kloopzcm.KLOOPZCM);

        addInParameter(P_CI_RELATION_ID);
        addInParameter(P_DELETE4REAL);
    }

    /**
     * Set the <code>p_ci_relation_id</code> parameter IN value to the routine
     */
    public void setPCiRelationId(Long value) {
        setValue(P_CI_RELATION_ID, value);
    }

    /**
     * Set the <code>p_delete4real</code> parameter IN value to the routine
     */
    public void setPDelete4real(Boolean value) {
        setValue(P_DELETE4REAL, value);
    }
}
