/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsAcquireLock extends AbstractRoutine<Boolean> {

    private static final long serialVersionUID = -49988601;

    /**
     * The parameter <code>kloopzcm.cms_acquire_lock.RETURN_VALUE</code>.
     */
    public static final Parameter<Boolean> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>kloopzcm.cms_acquire_lock.p_lock_name</code>.
     */
    public static final Parameter<String> P_LOCK_NAME = createParameter("p_lock_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cms_acquire_lock.p_locked_by</code>.
     */
    public static final Parameter<String> P_LOCKED_BY = createParameter("p_locked_by", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cms_acquire_lock.p_stale_timeout</code>.
     */
    public static final Parameter<Integer> P_STALE_TIMEOUT = createParameter("p_stale_timeout", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public CmsAcquireLock() {
        super("cms_acquire_lock", Kloopzcm.KLOOPZCM, org.jooq.impl.SQLDataType.BOOLEAN);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_LOCK_NAME);
        addInParameter(P_LOCKED_BY);
        addInParameter(P_STALE_TIMEOUT);
    }

    /**
     * Set the <code>p_lock_name</code> parameter IN value to the routine
     */
    public void setPLockName(String value) {
        setValue(P_LOCK_NAME, value);
    }

    /**
     * Set the <code>p_lock_name</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPLockName(Field<String> field) {
        setField(P_LOCK_NAME, field);
    }

    /**
     * Set the <code>p_locked_by</code> parameter IN value to the routine
     */
    public void setPLockedBy(String value) {
        setValue(P_LOCKED_BY, value);
    }

    /**
     * Set the <code>p_locked_by</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPLockedBy(Field<String> field) {
        setField(P_LOCKED_BY, field);
    }

    /**
     * Set the <code>p_stale_timeout</code> parameter IN value to the routine
     */
    public void setPStaleTimeout(Integer value) {
        setValue(P_STALE_TIMEOUT, value);
    }

    /**
     * Set the <code>p_stale_timeout</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPStaleTimeout(Field<Integer> field) {
        setField(P_STALE_TIMEOUT, field);
    }
}
