/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsSetVar1 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -541439847;

    /**
     * The parameter <code>kloopzcm.cms_set_var.p_var_name</code>.
     */
    public static final Parameter<String> P_VAR_NAME = createParameter("p_var_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.cms_set_var.p_var_value</code>.
     */
    public static final Parameter<String> P_VAR_VALUE = createParameter("p_var_value", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>kloopzcm.cms_set_var.p_updated_by</code>.
     */
    public static final Parameter<String> P_UPDATED_BY = createParameter("p_updated_by", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public CmsSetVar1() {
        super("cms_set_var", Kloopzcm.KLOOPZCM);

        addInParameter(P_VAR_NAME);
        addInParameter(P_VAR_VALUE);
        addInParameter(P_UPDATED_BY);
        setOverloaded(true);
    }

    /**
     * Set the <code>p_var_name</code> parameter IN value to the routine
     */
    public void setPVarName(String value) {
        setValue(P_VAR_NAME, value);
    }

    /**
     * Set the <code>p_var_value</code> parameter IN value to the routine
     */
    public void setPVarValue(String value) {
        setValue(P_VAR_VALUE, value);
    }

    /**
     * Set the <code>p_updated_by</code> parameter IN value to the routine
     */
    public void setPUpdatedBy(String value) {
        setValue(P_UPDATED_BY, value);
    }
}
