/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmUpdateOpsProcedureState extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1671050405;

    /**
     * The parameter <code>kloopzcm.cm_update_ops_procedure_state.p_proc_id</code>.
     */
    public static final Parameter<Long> P_PROC_ID = createParameter("p_proc_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.cm_update_ops_procedure_state.p_state</code>.
     */
    public static final Parameter<String> P_STATE = createParameter("p_state", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public CmUpdateOpsProcedureState() {
        super("cm_update_ops_procedure_state", Kloopzcm.KLOOPZCM);

        addInParameter(P_PROC_ID);
        addInParameter(P_STATE);
    }

    /**
     * Set the <code>p_proc_id</code> parameter IN value to the routine
     */
    public void setPProcId(Long value) {
        setValue(P_PROC_ID, value);
    }

    /**
     * Set the <code>p_state</code> parameter IN value to the routine
     */
    public void setPState(String value) {
        setValue(P_STATE, value);
    }
}
