/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmVacNs1 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1893164830;

    /**
     * The parameter <code>kloopzcm.cm_vac_ns.p_ns_id</code>.
     */
    public static final Parameter<Long> P_NS_ID = createParameter("p_ns_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public CmVacNs1() {
        super("cm_vac_ns", Kloopzcm.KLOOPZCM);

        addInParameter(P_NS_ID);
        setOverloaded(true);
    }

    /**
     * Set the <code>p_ns_id</code> parameter IN value to the routine
     */
    public void setPNsId(Long value) {
        setValue(P_NS_ID, value);
    }
}
