/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CopyOverAutoFlags extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 490118396;

    /**
     * Create a new routine call instance
     */
    public CopyOverAutoFlags() {
        super("copy_over_auto_flags", Kloopzcm.KLOOPZCM);
    }
}
