/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjCommitRelease extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 2036711447;

    /**
     * The parameter <code>kloopzcm.dj_commit_release.p_release_id</code>.
     */
    public static final Parameter<Long> P_RELEASE_ID = createParameter("p_release_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.dj_commit_release.p_set_df_value</code>.
     */
    public static final Parameter<Boolean> P_SET_DF_VALUE = createParameter("p_set_df_value", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>kloopzcm.dj_commit_release.p_new_ci_state_id</code>.
     */
    public static final Parameter<Integer> P_NEW_CI_STATE_ID = createParameter("p_new_ci_state_id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>kloopzcm.dj_commit_release.p_delete4real</code>.
     */
    public static final Parameter<Boolean> P_DELETE4REAL = createParameter("p_delete4real", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>kloopzcm.dj_commit_release.p_commited_by</code>.
     */
    public static final Parameter<String> P_COMMITED_BY = createParameter("p_commited_by", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.dj_commit_release.p_desc</code>.
     */
    public static final Parameter<String> P_DESC = createParameter("p_desc", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public DjCommitRelease() {
        super("dj_commit_release", Kloopzcm.KLOOPZCM);

        addInParameter(P_RELEASE_ID);
        addInParameter(P_SET_DF_VALUE);
        addInParameter(P_NEW_CI_STATE_ID);
        addInParameter(P_DELETE4REAL);
        addInParameter(P_COMMITED_BY);
        addInParameter(P_DESC);
    }

    /**
     * Set the <code>p_release_id</code> parameter IN value to the routine
     */
    public void setPReleaseId(Long value) {
        setValue(P_RELEASE_ID, value);
    }

    /**
     * Set the <code>p_set_df_value</code> parameter IN value to the routine
     */
    public void setPSetDfValue(Boolean value) {
        setValue(P_SET_DF_VALUE, value);
    }

    /**
     * Set the <code>p_new_ci_state_id</code> parameter IN value to the routine
     */
    public void setPNewCiStateId(Integer value) {
        setValue(P_NEW_CI_STATE_ID, value);
    }

    /**
     * Set the <code>p_delete4real</code> parameter IN value to the routine
     */
    public void setPDelete4real(Boolean value) {
        setValue(P_DELETE4REAL, value);
    }

    /**
     * Set the <code>p_commited_by</code> parameter IN value to the routine
     */
    public void setPCommitedBy(String value) {
        setValue(P_COMMITED_BY, value);
    }

    /**
     * Set the <code>p_desc</code> parameter IN value to the routine
     */
    public void setPDesc(String value) {
        setValue(P_DESC, value);
    }
}
