/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjCreateDpmtApproval extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1925187261;

    /**
     * The parameter <code>kloopzcm.dj_create_dpmt_approval.p_dpmt_id</code>.
     */
    public static final Parameter<Long> P_DPMT_ID = createParameter("p_dpmt_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.dj_create_dpmt_approval.p_govern_ci_id</code>.
     */
    public static final Parameter<Long> P_GOVERN_CI_ID = createParameter("p_govern_ci_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.dj_create_dpmt_approval.p_govern_ci</code>.
     */
    public static final Parameter<String> P_GOVERN_CI = createParameter("p_govern_ci", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>kloopzcm.dj_create_dpmt_approval.p_expires_in</code>.
     */
    public static final Parameter<Integer> P_EXPIRES_IN = createParameter("p_expires_in", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>kloopzcm.dj_create_dpmt_approval.out_approval_id</code>.
     */
    public static final Parameter<Long> OUT_APPROVAL_ID = createParameter("out_approval_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public DjCreateDpmtApproval() {
        super("dj_create_dpmt_approval", Kloopzcm.KLOOPZCM);

        addInParameter(P_DPMT_ID);
        addInParameter(P_GOVERN_CI_ID);
        addInParameter(P_GOVERN_CI);
        addInParameter(P_EXPIRES_IN);
        addOutParameter(OUT_APPROVAL_ID);
    }

    /**
     * Set the <code>p_dpmt_id</code> parameter IN value to the routine
     */
    public void setPDpmtId(Long value) {
        setValue(P_DPMT_ID, value);
    }

    /**
     * Set the <code>p_govern_ci_id</code> parameter IN value to the routine
     */
    public void setPGovernCiId(Long value) {
        setValue(P_GOVERN_CI_ID, value);
    }

    /**
     * Set the <code>p_govern_ci</code> parameter IN value to the routine
     */
    public void setPGovernCi(String value) {
        setValue(P_GOVERN_CI, value);
    }

    /**
     * Set the <code>p_expires_in</code> parameter IN value to the routine
     */
    public void setPExpiresIn(Integer value) {
        setValue(P_EXPIRES_IN, value);
    }

    /**
     * Get the <code>out_approval_id</code> parameter OUT value from the routine
     */
    public Long getOutApprovalId() {
        return get(OUT_APPROVAL_ID);
    }
}
