/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjDpmtApprove extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1109864787;

    /**
     * The parameter <code>kloopzcm.dj_dpmt_approve.p_approval_id</code>.
     */
    public static final Parameter<Long> P_APPROVAL_ID = createParameter("p_approval_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.dj_dpmt_approve.p_updated_by</code>.
     */
    public static final Parameter<String> P_UPDATED_BY = createParameter("p_updated_by", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.dj_dpmt_approve.p_expires_in</code>.
     */
    public static final Parameter<Integer> P_EXPIRES_IN = createParameter("p_expires_in", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>kloopzcm.dj_dpmt_approve.p_comments</code>.
     */
    public static final Parameter<String> P_COMMENTS = createParameter("p_comments", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public DjDpmtApprove() {
        super("dj_dpmt_approve", Kloopzcm.KLOOPZCM);

        addInParameter(P_APPROVAL_ID);
        addInParameter(P_UPDATED_BY);
        addInParameter(P_EXPIRES_IN);
        addInParameter(P_COMMENTS);
    }

    /**
     * Set the <code>p_approval_id</code> parameter IN value to the routine
     */
    public void setPApprovalId(Long value) {
        setValue(P_APPROVAL_ID, value);
    }

    /**
     * Set the <code>p_updated_by</code> parameter IN value to the routine
     */
    public void setPUpdatedBy(String value) {
        setValue(P_UPDATED_BY, value);
    }

    /**
     * Set the <code>p_expires_in</code> parameter IN value to the routine
     */
    public void setPExpiresIn(Integer value) {
        setValue(P_EXPIRES_IN, value);
    }

    /**
     * Set the <code>p_comments</code> parameter IN value to the routine
     */
    public void setPComments(String value) {
        setValue(P_COMMENTS, value);
    }
}
