/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjPromoteRfcRelations extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1858310264;

    /**
     * The parameter <code>kloopzcm.dj_promote_rfc_relations.p_rfc_id</code>.
     */
    public static final Parameter<Long> P_RFC_ID = createParameter("p_rfc_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.dj_promote_rfc_relations.p_set_df_value</code>.
     */
    public static final Parameter<Boolean> P_SET_DF_VALUE = createParameter("p_set_df_value", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>kloopzcm.dj_promote_rfc_relations.p_new_ci_state_id</code>.
     */
    public static final Parameter<Integer> P_NEW_CI_STATE_ID = createParameter("p_new_ci_state_id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public DjPromoteRfcRelations() {
        super("dj_promote_rfc_relations", Kloopzcm.KLOOPZCM);

        addInParameter(P_RFC_ID);
        addInParameter(P_SET_DF_VALUE);
        addInParameter(P_NEW_CI_STATE_ID);
    }

    /**
     * Set the <code>p_rfc_id</code> parameter IN value to the routine
     */
    public void setPRfcId(Long value) {
        setValue(P_RFC_ID, value);
    }

    /**
     * Set the <code>p_set_df_value</code> parameter IN value to the routine
     */
    public void setPSetDfValue(Boolean value) {
        setValue(P_SET_DF_VALUE, value);
    }

    /**
     * Set the <code>p_new_ci_state_id</code> parameter IN value to the routine
     */
    public void setPNewCiStateId(Integer value) {
        setValue(P_NEW_CI_STATE_ID, value);
    }
}
