/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjRmRfcs extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = 103988730;

    /**
     * The parameter <code>kloopzcm.dj_rm_rfcs.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>kloopzcm.dj_rm_rfcs.p_ns_path</code>.
     */
    public static final Parameter<String> P_NS_PATH = createParameter("p_ns_path", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public DjRmRfcs() {
        super("dj_rm_rfcs", Kloopzcm.KLOOPZCM, org.jooq.impl.SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_NS_PATH);
    }

    /**
     * Set the <code>p_ns_path</code> parameter IN value to the routine
     */
    public void setPNsPath(String value) {
        setValue(P_NS_PATH, value);
    }

    /**
     * Set the <code>p_ns_path</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPNsPath(Field<String> field) {
        setField(P_NS_PATH, field);
    }
}
