/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjUpsertRfcRelAttr extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -99639407;

    /**
     * The parameter <code>kloopzcm.dj_upsert_rfc_rel_attr.p_rfc_id</code>.
     */
    public static final Parameter<Long> P_RFC_ID = createParameter("p_rfc_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.dj_upsert_rfc_rel_attr.p_attribute_id</code>.
     */
    public static final Parameter<Integer> P_ATTRIBUTE_ID = createParameter("p_attribute_id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>kloopzcm.dj_upsert_rfc_rel_attr.p_new_attr_value</code>.
     */
    public static final Parameter<String> P_NEW_ATTR_VALUE = createParameter("p_new_attr_value", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>kloopzcm.dj_upsert_rfc_rel_attr.p_owner</code>.
     */
    public static final Parameter<String> P_OWNER = createParameter("p_owner", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.dj_upsert_rfc_rel_attr.p_comments</code>.
     */
    public static final Parameter<String> P_COMMENTS = createParameter("p_comments", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.dj_upsert_rfc_rel_attr.p_rfc_attr_id</code>.
     */
    public static final Parameter<Long> P_RFC_ATTR_ID = createParameter("p_rfc_attr_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public DjUpsertRfcRelAttr() {
        super("dj_upsert_rfc_rel_attr", Kloopzcm.KLOOPZCM);

        addInParameter(P_RFC_ID);
        addInParameter(P_ATTRIBUTE_ID);
        addInParameter(P_NEW_ATTR_VALUE);
        addInParameter(P_OWNER);
        addInParameter(P_COMMENTS);
        addOutParameter(P_RFC_ATTR_ID);
    }

    /**
     * Set the <code>p_rfc_id</code> parameter IN value to the routine
     */
    public void setPRfcId(Long value) {
        setValue(P_RFC_ID, value);
    }

    /**
     * Set the <code>p_attribute_id</code> parameter IN value to the routine
     */
    public void setPAttributeId(Integer value) {
        setValue(P_ATTRIBUTE_ID, value);
    }

    /**
     * Set the <code>p_new_attr_value</code> parameter IN value to the routine
     */
    public void setPNewAttrValue(String value) {
        setValue(P_NEW_ATTR_VALUE, value);
    }

    /**
     * Set the <code>p_owner</code> parameter IN value to the routine
     */
    public void setPOwner(String value) {
        setValue(P_OWNER, value);
    }

    /**
     * Set the <code>p_comments</code> parameter IN value to the routine
     */
    public void setPComments(String value) {
        setValue(P_COMMENTS, value);
    }

    /**
     * Get the <code>p_rfc_attr_id</code> parameter OUT value from the routine
     */
    public Long getPRfcAttrId() {
        return get(P_RFC_ATTR_ID);
    }
}
