/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjUpdateRfcRelation2 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -450854420;

    /**
     * The parameter <code>kloopzcm.dj_update_rfc_relation.p_rfc_id</code>.
     */
    public static final Parameter<Long> P_RFC_ID = createParameter("p_rfc_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.dj_update_rfc_relation.p_exec_order</code>.
     */
    public static final Parameter<Integer> P_EXEC_ORDER = createParameter("p_exec_order", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>kloopzcm.dj_update_rfc_relation.p_comments</code>.
     */
    public static final Parameter<String> P_COMMENTS = createParameter("p_comments", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.dj_update_rfc_relation.p_updated_by</code>.
     */
    public static final Parameter<String> P_UPDATED_BY = createParameter("p_updated_by", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.dj_update_rfc_relation.p_release_id</code>.
     */
    public static final Parameter<Long> P_RELEASE_ID = createParameter("p_release_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public DjUpdateRfcRelation2() {
        super("dj_update_rfc_relation", Kloopzcm.KLOOPZCM);

        addInParameter(P_RFC_ID);
        addInParameter(P_EXEC_ORDER);
        addInParameter(P_COMMENTS);
        addInParameter(P_UPDATED_BY);
        addInParameter(P_RELEASE_ID);
        setOverloaded(true);
    }

    /**
     * Set the <code>p_rfc_id</code> parameter IN value to the routine
     */
    public void setPRfcId(Long value) {
        setValue(P_RFC_ID, value);
    }

    /**
     * Set the <code>p_exec_order</code> parameter IN value to the routine
     */
    public void setPExecOrder(Integer value) {
        setValue(P_EXEC_ORDER, value);
    }

    /**
     * Set the <code>p_comments</code> parameter IN value to the routine
     */
    public void setPComments(String value) {
        setValue(P_COMMENTS, value);
    }

    /**
     * Set the <code>p_updated_by</code> parameter IN value to the routine
     */
    public void setPUpdatedBy(String value) {
        setValue(P_UPDATED_BY, value);
    }

    /**
     * Set the <code>p_release_id</code> parameter IN value to the routine
     */
    public void setPReleaseId(Long value) {
        setValue(P_RELEASE_ID, value);
    }
}
