/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjUpdDeploymentState extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 873667254;

    /**
     * The parameter <code>kloopzcm.dj_upd_deployment_state.p_deployment_id</code>.
     */
    public static final Parameter<Long> P_DEPLOYMENT_ID = createParameter("p_deployment_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>kloopzcm.dj_upd_deployment_state.p_state</code>.
     */
    public static final Parameter<String> P_STATE = createParameter("p_state", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.dj_upd_deployment_state.p_updated_by</code>.
     */
    public static final Parameter<String> P_UPDATED_BY = createParameter("p_updated_by", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>kloopzcm.dj_upd_deployment_state.p_desc</code>.
     */
    public static final Parameter<String> P_DESC = createParameter("p_desc", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public DjUpdDeploymentState() {
        super("dj_upd_deployment_state", Kloopzcm.KLOOPZCM);

        addInParameter(P_DEPLOYMENT_ID);
        addInParameter(P_STATE);
        addInParameter(P_UPDATED_BY);
        addInParameter(P_DESC);
    }

    /**
     * Set the <code>p_deployment_id</code> parameter IN value to the routine
     */
    public void setPDeploymentId(Long value) {
        setValue(P_DEPLOYMENT_ID, value);
    }

    /**
     * Set the <code>p_state</code> parameter IN value to the routine
     */
    public void setPState(String value) {
        setValue(P_STATE, value);
    }

    /**
     * Set the <code>p_updated_by</code> parameter IN value to the routine
     */
    public void setPUpdatedBy(String value) {
        setValue(P_UPDATED_BY, value);
    }

    /**
     * Set the <code>p_desc</code> parameter IN value to the routine
     */
    public void setPDesc(String value) {
        setValue(P_DESC, value);
    }
}
