/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.routines;


import com.oneops.crawler.jooq.cms.Kloopzcm;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ForceCompleteDpmt extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -542633329;

    /**
     * The parameter <code>kloopzcm.force_complete_dpmt.p_dpmt_id</code>.
     */
    public static final Parameter<Long> P_DPMT_ID = createParameter("p_dpmt_id", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public ForceCompleteDpmt() {
        super("force_complete_dpmt", Kloopzcm.KLOOPZCM);

        addInParameter(P_DPMT_ID);
    }

    /**
     * Set the <code>p_dpmt_id</code> parameter IN value to the routine
     */
    public void setPDpmtId(Long value) {
        setValue(P_DPMT_ID, value);
    }
}
