source 'http://rubygems.org'

gem 'mixlib-shellout', '1.3.0'
gem 'mime-types', '1.25'
gem 'net-ssh', '2.6.5'
gem 'rake', '10.1.1'
gem 'chef', '11.4'
gem 'activesupport', '3.1.12'
gem 'activeresource', '3.1.12'
gem 'activemodel', '3.1.12'
gem 'fog', '1.23.0'
gem 'ohai', '6.22.0'
gem 'nokogiri', '1.5.11'
gem 'json', '1.7.7'
gem 'oneops-admin', '1.0.0'
gem 'kramdown'

platforms :mingw do
  gem 'win32-open3'
  gem 'ruby-wmi'
  gem 'windows-api'
  gem 'windows-pr'
end
