/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in kloopzcm
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>kloopzcm.cm_pk_seq</code>
     */
    public static final Sequence<Long> CM_PK_SEQ = new SequenceImpl<Long>("cm_pk_seq", Kloopzcm.KLOOPZCM, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>kloopzcm.dj_pk_seq</code>
     */
    public static final Sequence<Long> DJ_PK_SEQ = new SequenceImpl<Long>("dj_pk_seq", Kloopzcm.KLOOPZCM, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>kloopzcm.event_pk_seq</code>
     */
    public static final Sequence<Long> EVENT_PK_SEQ = new SequenceImpl<Long>("event_pk_seq", Kloopzcm.KLOOPZCM, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>kloopzcm.log_pk_seq</code>
     */
    public static final Sequence<Long> LOG_PK_SEQ = new SequenceImpl<Long>("log_pk_seq", Kloopzcm.KLOOPZCM, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>kloopzcm.md_pk_seq</code>
     */
    public static final Sequence<Long> MD_PK_SEQ = new SequenceImpl<Long>("md_pk_seq", Kloopzcm.KLOOPZCM, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>kloopzcm.ns_pk_seq</code>
     */
    public static final Sequence<Long> NS_PK_SEQ = new SequenceImpl<Long>("ns_pk_seq", Kloopzcm.KLOOPZCM, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
