/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.crawler;


import com.oneops.crawler.jooq.crawler.tables.CrawlEntities;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Crawler extends SchemaImpl {

    private static final long serialVersionUID = -290778912;

    /**
     * The reference instance of <code>crawler</code>
     */
    public static final Crawler CRAWLER = new Crawler();

    /**
     * The table <code>crawler.crawl_entities</code>.
     */
    public final CrawlEntities CRAWL_ENTITIES = com.oneops.crawler.jooq.crawler.tables.CrawlEntities.CRAWL_ENTITIES;

    /**
     * No further instances allowed
     */
    private Crawler() {
        super("crawler", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CrawlEntities.CRAWL_ENTITIES);
    }
}
