/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.crawler;


import com.oneops.crawler.jooq.crawler.tables.CrawlEntities;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>crawler</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CRAWL_ENTITIES_PKEY = Indexes0.CRAWL_ENTITIES_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index CRAWL_ENTITIES_PKEY = createIndex("crawl_entities_pkey", CrawlEntities.CRAWL_ENTITIES, new OrderField[] { CrawlEntities.CRAWL_ENTITIES.OO_ID }, true);
    }
}
