/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.crawler;


import com.oneops.crawler.jooq.crawler.tables.CrawlEntities;
import com.oneops.crawler.jooq.crawler.tables.records.CrawlEntitiesRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>crawler</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CrawlEntitiesRecord> CRAWL_ENTITIES_PKEY = UniqueKeys0.CRAWL_ENTITIES_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CrawlEntitiesRecord> CRAWL_ENTITIES_PKEY = createUniqueKey(CrawlEntities.CRAWL_ENTITIES, "crawl_entities_pkey", CrawlEntities.CRAWL_ENTITIES.OO_ID);
    }
}
