/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.crawler.tables;


import com.oneops.crawler.jooq.crawler.Crawler;
import com.oneops.crawler.jooq.crawler.Indexes;
import com.oneops.crawler.jooq.crawler.Keys;
import com.oneops.crawler.jooq.crawler.tables.records.CrawlEntitiesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrawlEntities extends TableImpl<CrawlEntitiesRecord> {

    private static final long serialVersionUID = -1703379493;

    /**
     * The reference instance of <code>crawler.crawl_entities</code>
     */
    public static final CrawlEntities CRAWL_ENTITIES = new CrawlEntities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CrawlEntitiesRecord> getRecordType() {
        return CrawlEntitiesRecord.class;
    }

    /**
     * The column <code>crawler.crawl_entities.ns_path</code>.
     */
    public final TableField<CrawlEntitiesRecord, String> NS_PATH = createField("ns_path", org.jooq.impl.SQLDataType.VARCHAR(300), this, "");

    /**
     * The column <code>crawler.crawl_entities.created</code>.
     */
    public final TableField<CrawlEntitiesRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>crawler.crawl_entities.last_crawled_at</code>.
     */
    public final TableField<CrawlEntitiesRecord, Timestamp> LAST_CRAWLED_AT = createField("last_crawled_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>crawler.crawl_entities.oo_id</code>.
     */
    public final TableField<CrawlEntitiesRecord, Long> OO_ID = createField("oo_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>crawler.crawl_entities</code> table reference
     */
    public CrawlEntities() {
        this(DSL.name("crawl_entities"), null);
    }

    /**
     * Create an aliased <code>crawler.crawl_entities</code> table reference
     */
    public CrawlEntities(String alias) {
        this(DSL.name(alias), CRAWL_ENTITIES);
    }

    /**
     * Create an aliased <code>crawler.crawl_entities</code> table reference
     */
    public CrawlEntities(Name alias) {
        this(alias, CRAWL_ENTITIES);
    }

    private CrawlEntities(Name alias, Table<CrawlEntitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private CrawlEntities(Name alias, Table<CrawlEntitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Crawler.CRAWLER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CRAWL_ENTITIES_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CrawlEntitiesRecord> getPrimaryKey() {
        return Keys.CRAWL_ENTITIES_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CrawlEntitiesRecord>> getKeys() {
        return Arrays.<UniqueKey<CrawlEntitiesRecord>>asList(Keys.CRAWL_ENTITIES_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrawlEntities as(String alias) {
        return new CrawlEntities(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CrawlEntities as(Name alias) {
        return new CrawlEntities(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CrawlEntities rename(String name) {
        return new CrawlEntities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CrawlEntities rename(Name name) {
        return new CrawlEntities(name, null);
    }
}
