/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.CmCiRelationAttributes;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmCiRelationAttributesRecord extends UpdatableRecordImpl<CmCiRelationAttributesRecord> implements Record9<Long, Long, Integer, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 839189310;

    /**
     * Setter for <code>kloopzcm.cm_ci_relation_attributes.ci_rel_attribute_id</code>.
     */
    public void setCiRelAttributeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ci_relation_attributes.ci_rel_attribute_id</code>.
     */
    public Long getCiRelAttributeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kloopzcm.cm_ci_relation_attributes.ci_relation_id</code>.
     */
    public void setCiRelationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ci_relation_attributes.ci_relation_id</code>.
     */
    public Long getCiRelationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kloopzcm.cm_ci_relation_attributes.attribute_id</code>.
     */
    public void setAttributeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ci_relation_attributes.attribute_id</code>.
     */
    public Integer getAttributeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kloopzcm.cm_ci_relation_attributes.df_attribute_value</code>.
     */
    public void setDfAttributeValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ci_relation_attributes.df_attribute_value</code>.
     */
    public String getDfAttributeValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kloopzcm.cm_ci_relation_attributes.dj_attribute_value</code>.
     */
    public void setDjAttributeValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ci_relation_attributes.dj_attribute_value</code>.
     */
    public String getDjAttributeValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kloopzcm.cm_ci_relation_attributes.owner</code>.
     */
    public void setOwner(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ci_relation_attributes.owner</code>.
     */
    public String getOwner() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kloopzcm.cm_ci_relation_attributes.comments</code>.
     */
    public void setComments(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ci_relation_attributes.comments</code>.
     */
    public String getComments() {
        return (String) get(6);
    }

    /**
     * Setter for <code>kloopzcm.cm_ci_relation_attributes.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ci_relation_attributes.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>kloopzcm.cm_ci_relation_attributes.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ci_relation_attributes.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Integer, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Integer, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES.CI_REL_ATTRIBUTE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES.CI_RELATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES.ATTRIBUTE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES.DF_ATTRIBUTE_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES.DJ_ATTRIBUTE_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES.COMMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getCiRelAttributeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCiRelationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAttributeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDfAttributeValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDjAttributeValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCiRelAttributeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCiRelationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAttributeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDfAttributeValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDjAttributeValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord value1(Long value) {
        setCiRelAttributeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord value2(Long value) {
        setCiRelationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord value3(Integer value) {
        setAttributeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord value4(String value) {
        setDfAttributeValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord value5(String value) {
        setDjAttributeValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord value6(String value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord value7(String value) {
        setComments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord value8(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord value9(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmCiRelationAttributesRecord values(Long value1, Long value2, Integer value3, String value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmCiRelationAttributesRecord
     */
    public CmCiRelationAttributesRecord() {
        super(CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES);
    }

    /**
     * Create a detached, initialised CmCiRelationAttributesRecord
     */
    public CmCiRelationAttributesRecord(Long ciRelAttributeId, Long ciRelationId, Integer attributeId, String dfAttributeValue, String djAttributeValue, String owner, String comments, Timestamp created, Timestamp updated) {
        super(CmCiRelationAttributes.CM_CI_RELATION_ATTRIBUTES);

        set(0, ciRelAttributeId);
        set(1, ciRelationId);
        set(2, attributeId);
        set(3, dfAttributeValue);
        set(4, djAttributeValue);
        set(5, owner);
        set(6, comments);
        set(7, created);
        set(8, updated);
    }
}
