/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.CmOpsActions;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmOpsActionsRecord extends UpdatableRecordImpl<CmOpsActionsRecord> implements Record12<Long, Long, Long, String, String, String, Integer, Integer, Boolean, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 616168780;

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.ops_action_id</code>.
     */
    public void setOpsActionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.ops_action_id</code>.
     */
    public Long getOpsActionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.ops_proc_id</code>.
     */
    public void setOpsProcId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.ops_proc_id</code>.
     */
    public Long getOpsProcId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.ci_id</code>.
     */
    public void setCiId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.ci_id</code>.
     */
    public Long getCiId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.action_name</code>.
     */
    public void setActionName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.action_name</code>.
     */
    public String getActionName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.arglist</code>.
     */
    public void setArglist(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.arglist</code>.
     */
    public String getArglist() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.payload</code>.
     */
    public void setPayload(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.payload</code>.
     */
    public String getPayload() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.exec_order</code>.
     */
    public void setExecOrder(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.exec_order</code>.
     */
    public Integer getExecOrder() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.state_id</code>.
     */
    public void setStateId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.state_id</code>.
     */
    public Integer getStateId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.is_critical</code>.
     */
    public void setIsCritical(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.is_critical</code>.
     */
    public Boolean getIsCritical() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.extra_info</code>.
     */
    public void setExtraInfo(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.extra_info</code>.
     */
    public String getExtraInfo() {
        return (String) get(9);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>kloopzcm.cm_ops_actions.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>kloopzcm.cm_ops_actions.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, Long, String, String, String, Integer, Integer, Boolean, String, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, Long, String, String, String, Integer, Integer, Boolean, String, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CmOpsActions.CM_OPS_ACTIONS.OPS_ACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return CmOpsActions.CM_OPS_ACTIONS.OPS_PROC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return CmOpsActions.CM_OPS_ACTIONS.CI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CmOpsActions.CM_OPS_ACTIONS.ACTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CmOpsActions.CM_OPS_ACTIONS.ARGLIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CmOpsActions.CM_OPS_ACTIONS.PAYLOAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return CmOpsActions.CM_OPS_ACTIONS.EXEC_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return CmOpsActions.CM_OPS_ACTIONS.STATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return CmOpsActions.CM_OPS_ACTIONS.IS_CRITICAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CmOpsActions.CM_OPS_ACTIONS.EXTRA_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return CmOpsActions.CM_OPS_ACTIONS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return CmOpsActions.CM_OPS_ACTIONS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getOpsActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getOpsProcId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getCiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getArglist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getExecOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getIsCritical();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getExtraInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOpsActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getOpsProcId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getArglist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getExecOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getIsCritical();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getExtraInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value1(Long value) {
        setOpsActionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value2(Long value) {
        setOpsProcId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value3(Long value) {
        setCiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value4(String value) {
        setActionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value5(String value) {
        setArglist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value6(String value) {
        setPayload(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value7(Integer value) {
        setExecOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value8(Integer value) {
        setStateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value9(Boolean value) {
        setIsCritical(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value10(String value) {
        setExtraInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value11(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord value12(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmOpsActionsRecord values(Long value1, Long value2, Long value3, String value4, String value5, String value6, Integer value7, Integer value8, Boolean value9, String value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmOpsActionsRecord
     */
    public CmOpsActionsRecord() {
        super(CmOpsActions.CM_OPS_ACTIONS);
    }

    /**
     * Create a detached, initialised CmOpsActionsRecord
     */
    public CmOpsActionsRecord(Long opsActionId, Long opsProcId, Long ciId, String actionName, String arglist, String payload, Integer execOrder, Integer stateId, Boolean isCritical, String extraInfo, Timestamp created, Timestamp updated) {
        super(CmOpsActions.CM_OPS_ACTIONS);

        set(0, opsActionId);
        set(1, opsProcId);
        set(2, ciId);
        set(3, actionName);
        set(4, arglist);
        set(5, payload);
        set(6, execOrder);
        set(7, stateId);
        set(8, isCritical);
        set(9, extraInfo);
        set(10, created);
        set(11, updated);
    }
}
