/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.CmsEventQueue;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsEventQueueRecord extends UpdatableRecordImpl<CmsEventQueueRecord> implements Record5<Long, Long, String, Integer, Timestamp> {

    private static final long serialVersionUID = 1554006609;

    /**
     * Setter for <code>kloopzcm.cms_event_queue.event_id</code>.
     */
    public void setEventId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_event_queue.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kloopzcm.cms_event_queue.source_pk</code>.
     */
    public void setSourcePk(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_event_queue.source_pk</code>.
     */
    public Long getSourcePk() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kloopzcm.cms_event_queue.source_name</code>.
     */
    public void setSourceName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_event_queue.source_name</code>.
     */
    public String getSourceName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kloopzcm.cms_event_queue.event_type_id</code>.
     */
    public void setEventTypeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_event_queue.event_type_id</code>.
     */
    public Integer getEventTypeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>kloopzcm.cms_event_queue.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_event_queue.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, String, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, String, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CmsEventQueue.CMS_EVENT_QUEUE.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return CmsEventQueue.CMS_EVENT_QUEUE.SOURCE_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CmsEventQueue.CMS_EVENT_QUEUE.SOURCE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return CmsEventQueue.CMS_EVENT_QUEUE.EVENT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return CmsEventQueue.CMS_EVENT_QUEUE.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getSourcePk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSourceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getEventTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSourcePk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSourceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getEventTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsEventQueueRecord value1(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsEventQueueRecord value2(Long value) {
        setSourcePk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsEventQueueRecord value3(String value) {
        setSourceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsEventQueueRecord value4(Integer value) {
        setEventTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsEventQueueRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsEventQueueRecord values(Long value1, Long value2, String value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmsEventQueueRecord
     */
    public CmsEventQueueRecord() {
        super(CmsEventQueue.CMS_EVENT_QUEUE);
    }

    /**
     * Create a detached, initialised CmsEventQueueRecord
     */
    public CmsEventQueueRecord(Long eventId, Long sourcePk, String sourceName, Integer eventTypeId, Timestamp created) {
        super(CmsEventQueue.CMS_EVENT_QUEUE);

        set(0, eventId);
        set(1, sourcePk);
        set(2, sourceName);
        set(3, eventTypeId);
        set(4, created);
    }
}
