/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.CmsLock;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsLockRecord extends UpdatableRecordImpl<CmsLockRecord> implements Record5<Long, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 321965410;

    /**
     * Setter for <code>kloopzcm.cms_lock.lock_id</code>.
     */
    public void setLockId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_lock.lock_id</code>.
     */
    public Long getLockId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kloopzcm.cms_lock.lock_name</code>.
     */
    public void setLockName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_lock.lock_name</code>.
     */
    public String getLockName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kloopzcm.cms_lock.locked_by</code>.
     */
    public void setLockedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_lock.locked_by</code>.
     */
    public String getLockedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kloopzcm.cms_lock.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_lock.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>kloopzcm.cms_lock.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_lock.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CmsLock.CMS_LOCK.LOCK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CmsLock.CMS_LOCK.LOCK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CmsLock.CMS_LOCK.LOCKED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return CmsLock.CMS_LOCK.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return CmsLock.CMS_LOCK.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getLockId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLockName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLockedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getLockId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLockName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLockedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsLockRecord value1(Long value) {
        setLockId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsLockRecord value2(String value) {
        setLockName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsLockRecord value3(String value) {
        setLockedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsLockRecord value4(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsLockRecord value5(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsLockRecord values(Long value1, String value2, String value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmsLockRecord
     */
    public CmsLockRecord() {
        super(CmsLock.CMS_LOCK);
    }

    /**
     * Create a detached, initialised CmsLockRecord
     */
    public CmsLockRecord(Long lockId, String lockName, String lockedBy, Timestamp created, Timestamp updated) {
        super(CmsLock.CMS_LOCK);

        set(0, lockId);
        set(1, lockName);
        set(2, lockedBy);
        set(3, created);
        set(4, updated);
    }
}
