/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.CmsVars;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsVarsRecord extends UpdatableRecordImpl<CmsVarsRecord> implements Record7<Long, String, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1089335380;

    /**
     * Setter for <code>kloopzcm.cms_vars.var_id</code>.
     */
    public void setVarId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_vars.var_id</code>.
     */
    public Long getVarId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kloopzcm.cms_vars.var_name</code>.
     */
    public void setVarName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_vars.var_name</code>.
     */
    public String getVarName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kloopzcm.cms_vars.var_value</code>.
     */
    public void setVarValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_vars.var_value</code>.
     */
    public String getVarValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kloopzcm.cms_vars.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_vars.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kloopzcm.cms_vars.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_vars.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>kloopzcm.cms_vars.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_vars.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>kloopzcm.cms_vars.criteria</code>.
     */
    public void setCriteria(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>kloopzcm.cms_vars.criteria</code>.
     */
    public String getCriteria() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CmsVars.CMS_VARS.VAR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CmsVars.CMS_VARS.VAR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CmsVars.CMS_VARS.VAR_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CmsVars.CMS_VARS.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return CmsVars.CMS_VARS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return CmsVars.CMS_VARS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CmsVars.CMS_VARS.CRITERIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getVarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getVarName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getVarValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCriteria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getVarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getVarName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getVarValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCriteria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsVarsRecord value1(Long value) {
        setVarId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsVarsRecord value2(String value) {
        setVarName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsVarsRecord value3(String value) {
        setVarValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsVarsRecord value4(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsVarsRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsVarsRecord value6(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsVarsRecord value7(String value) {
        setCriteria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsVarsRecord values(Long value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmsVarsRecord
     */
    public CmsVarsRecord() {
        super(CmsVars.CMS_VARS);
    }

    /**
     * Create a detached, initialised CmsVarsRecord
     */
    public CmsVarsRecord(Long varId, String varName, String varValue, String updatedBy, Timestamp created, Timestamp updated, String criteria) {
        super(CmsVars.CMS_VARS);

        set(0, varId);
        set(1, varName);
        set(2, varValue);
        set(3, updatedBy);
        set(4, created);
        set(5, updated);
        set(6, criteria);
    }
}
