/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.DjDpmtApprovals;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjDpmtApprovalsRecord extends UpdatableRecordImpl<DjDpmtApprovalsRecord> implements Record10<Long, Long, Long, String, Integer, String, Timestamp, Timestamp, Integer, String> {

    private static final long serialVersionUID = 1281765170;

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.approval_id</code>.
     */
    public void setApprovalId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.approval_id</code>.
     */
    public Long getApprovalId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.deployment_id</code>.
     */
    public void setDeploymentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.deployment_id</code>.
     */
    public Long getDeploymentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.govern_ci_id</code>.
     */
    public void setGovernCiId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.govern_ci_id</code>.
     */
    public Long getGovernCiId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.govern_ci</code>.
     */
    public void setGovernCi(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.govern_ci</code>.
     */
    public String getGovernCi() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.state_id</code>.
     */
    public void setStateId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.state_id</code>.
     */
    public Integer getStateId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.expires_in</code>.
     */
    public void setExpiresIn(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.expires_in</code>.
     */
    public Integer getExpiresIn() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>kloopzcm.dj_dpmt_approvals.comments</code>.
     */
    public void setComments(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_dpmt_approvals.comments</code>.
     */
    public String getComments() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, String, Integer, String, Timestamp, Timestamp, Integer, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, String, Integer, String, Timestamp, Timestamp, Integer, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.APPROVAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.DEPLOYMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.GOVERN_CI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.GOVERN_CI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.STATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.EXPIRES_IN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return DjDpmtApprovals.DJ_DPMT_APPROVALS.COMMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getApprovalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getDeploymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getGovernCiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getGovernCi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getExpiresIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getApprovalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getDeploymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getGovernCiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getGovernCi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getExpiresIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value1(Long value) {
        setApprovalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value2(Long value) {
        setDeploymentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value3(Long value) {
        setGovernCiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value4(String value) {
        setGovernCi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value5(Integer value) {
        setStateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value7(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value8(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value9(Integer value) {
        setExpiresIn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord value10(String value) {
        setComments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjDpmtApprovalsRecord values(Long value1, Long value2, Long value3, String value4, Integer value5, String value6, Timestamp value7, Timestamp value8, Integer value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DjDpmtApprovalsRecord
     */
    public DjDpmtApprovalsRecord() {
        super(DjDpmtApprovals.DJ_DPMT_APPROVALS);
    }

    /**
     * Create a detached, initialised DjDpmtApprovalsRecord
     */
    public DjDpmtApprovalsRecord(Long approvalId, Long deploymentId, Long governCiId, String governCi, Integer stateId, String updatedBy, Timestamp created, Timestamp updated, Integer expiresIn, String comments) {
        super(DjDpmtApprovals.DJ_DPMT_APPROVALS);

        set(0, approvalId);
        set(1, deploymentId);
        set(2, governCiId);
        set(3, governCi);
        set(4, stateId);
        set(5, updatedBy);
        set(6, created);
        set(7, updated);
        set(8, expiresIn);
        set(9, comments);
    }
}
