/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.DjReleaseRevLabel;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjReleaseRevLabelRecord extends UpdatableRecordImpl<DjReleaseRevLabelRecord> implements Record4<Long, Short, Long, Short> {

    private static final long serialVersionUID = 173683938;

    /**
     * Setter for <code>kloopzcm.dj_release_rev_label.release_id</code>.
     */
    public void setReleaseId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_release_rev_label.release_id</code>.
     */
    public Long getReleaseId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kloopzcm.dj_release_rev_label.revision</code>.
     */
    public void setRevision(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_release_rev_label.revision</code>.
     */
    public Short getRevision() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>kloopzcm.dj_release_rev_label.rfc_id</code>.
     */
    public void setRfcId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_release_rev_label.rfc_id</code>.
     */
    public Long getRfcId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>kloopzcm.dj_release_rev_label.target_id</code>.
     */
    public void setTargetId(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_release_rev_label.target_id</code>.
     */
    public Short getTargetId() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Long, Short, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Short, Long, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Short, Long, Short> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DjReleaseRevLabel.DJ_RELEASE_REV_LABEL.RELEASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return DjReleaseRevLabel.DJ_RELEASE_REV_LABEL.REVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return DjReleaseRevLabel.DJ_RELEASE_REV_LABEL.RFC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return DjReleaseRevLabel.DJ_RELEASE_REV_LABEL.TARGET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getReleaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component2() {
        return getRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getRfcId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getTargetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getReleaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getRfcId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getTargetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjReleaseRevLabelRecord value1(Long value) {
        setReleaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjReleaseRevLabelRecord value2(Short value) {
        setRevision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjReleaseRevLabelRecord value3(Long value) {
        setRfcId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjReleaseRevLabelRecord value4(Short value) {
        setTargetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjReleaseRevLabelRecord values(Long value1, Short value2, Long value3, Short value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DjReleaseRevLabelRecord
     */
    public DjReleaseRevLabelRecord() {
        super(DjReleaseRevLabel.DJ_RELEASE_REV_LABEL);
    }

    /**
     * Create a detached, initialised DjReleaseRevLabelRecord
     */
    public DjReleaseRevLabelRecord(Long releaseId, Short revision, Long rfcId, Short targetId) {
        super(DjReleaseRevLabel.DJ_RELEASE_REV_LABEL);

        set(0, releaseId);
        set(1, revision);
        set(2, rfcId);
        set(3, targetId);
    }
}
