/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.DjRfcCi;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjRfcCiRecord extends UpdatableRecordImpl<DjRfcCiRecord> implements Record17<Long, Long, Long, Long, Integer, String, String, Integer, String, String, Short, Boolean, Long, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = -821668008;

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.rfc_id</code>.
     */
    public void setRfcId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.rfc_id</code>.
     */
    public Long getRfcId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.release_id</code>.
     */
    public void setReleaseId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.release_id</code>.
     */
    public Long getReleaseId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.ci_id</code>.
     */
    public void setCiId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.ci_id</code>.
     */
    public Long getCiId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.ns_id</code>.
     */
    public void setNsId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.ns_id</code>.
     */
    public Long getNsId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.class_id</code>.
     */
    public void setClassId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.class_id</code>.
     */
    public Integer getClassId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.ci_name</code>.
     */
    public void setCiName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.ci_name</code>.
     */
    public String getCiName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.ci_goid</code>.
     */
    public void setCiGoid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.ci_goid</code>.
     */
    public String getCiGoid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.action_id</code>.
     */
    public void setActionId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.action_id</code>.
     */
    public Integer getActionId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.execution_order</code>.
     */
    public void setExecutionOrder(Short value) {
        set(10, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.execution_order</code>.
     */
    public Short getExecutionOrder() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.is_active_in_release</code>.
     */
    public void setIsActiveInRelease(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.is_active_in_release</code>.
     */
    public Boolean getIsActiveInRelease() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.last_rfc_id</code>.
     */
    public void setLastRfcId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.last_rfc_id</code>.
     */
    public Long getLastRfcId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.comments</code>.
     */
    public void setComments(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.comments</code>.
     */
    public String getComments() {
        return (String) get(13);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci.hint</code>.
     */
    public void setHint(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci.hint</code>.
     */
    public String getHint() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, Long, Long, Long, Integer, String, String, Integer, String, String, Short, Boolean, Long, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, Long, Long, Long, Integer, String, String, Integer, String, String, Short, Boolean, Long, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DjRfcCi.DJ_RFC_CI.RFC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return DjRfcCi.DJ_RFC_CI.RELEASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return DjRfcCi.DJ_RFC_CI.CI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return DjRfcCi.DJ_RFC_CI.NS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DjRfcCi.DJ_RFC_CI.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DjRfcCi.DJ_RFC_CI.CI_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DjRfcCi.DJ_RFC_CI.CI_GOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return DjRfcCi.DJ_RFC_CI.ACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DjRfcCi.DJ_RFC_CI.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return DjRfcCi.DJ_RFC_CI.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field11() {
        return DjRfcCi.DJ_RFC_CI.EXECUTION_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return DjRfcCi.DJ_RFC_CI.IS_ACTIVE_IN_RELEASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return DjRfcCi.DJ_RFC_CI.LAST_RFC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return DjRfcCi.DJ_RFC_CI.COMMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return DjRfcCi.DJ_RFC_CI.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return DjRfcCi.DJ_RFC_CI.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return DjRfcCi.DJ_RFC_CI.HINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getRfcId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getReleaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getCiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getNsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCiName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCiGoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component11() {
        return getExecutionOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getIsActiveInRelease();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getLastRfcId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getHint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getRfcId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getReleaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getNsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCiName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCiGoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value11() {
        return getExecutionOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getIsActiveInRelease();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getLastRfcId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getHint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value1(Long value) {
        setRfcId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value2(Long value) {
        setReleaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value3(Long value) {
        setCiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value4(Long value) {
        setNsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value5(Integer value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value6(String value) {
        setCiName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value7(String value) {
        setCiGoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value8(Integer value) {
        setActionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value9(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value10(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value11(Short value) {
        setExecutionOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value12(Boolean value) {
        setIsActiveInRelease(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value13(Long value) {
        setLastRfcId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value14(String value) {
        setComments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value15(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value16(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord value17(String value) {
        setHint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiRecord values(Long value1, Long value2, Long value3, Long value4, Integer value5, String value6, String value7, Integer value8, String value9, String value10, Short value11, Boolean value12, Long value13, String value14, Timestamp value15, Timestamp value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DjRfcCiRecord
     */
    public DjRfcCiRecord() {
        super(DjRfcCi.DJ_RFC_CI);
    }

    /**
     * Create a detached, initialised DjRfcCiRecord
     */
    public DjRfcCiRecord(Long rfcId, Long releaseId, Long ciId, Long nsId, Integer classId, String ciName, String ciGoid, Integer actionId, String createdBy, String updatedBy, Short executionOrder, Boolean isActiveInRelease, Long lastRfcId, String comments, Timestamp created, Timestamp updated, String hint) {
        super(DjRfcCi.DJ_RFC_CI);

        set(0, rfcId);
        set(1, releaseId);
        set(2, ciId);
        set(3, nsId);
        set(4, classId);
        set(5, ciName);
        set(6, ciGoid);
        set(7, actionId);
        set(8, createdBy);
        set(9, updatedBy);
        set(10, executionOrder);
        set(11, isActiveInRelease);
        set(12, lastRfcId);
        set(13, comments);
        set(14, created);
        set(15, updated);
        set(16, hint);
    }
}
