/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.DjRfcCiActions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjRfcCiActionsRecord extends UpdatableRecordImpl<DjRfcCiActionsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -204570697;

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci_actions.action_id</code>.
     */
    public void setActionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci_actions.action_id</code>.
     */
    public Integer getActionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kloopzcm.dj_rfc_ci_actions.action_name</code>.
     */
    public void setActionName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.dj_rfc_ci_actions.action_name</code>.
     */
    public String getActionName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DjRfcCiActions.DJ_RFC_CI_ACTIONS.ACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DjRfcCiActions.DJ_RFC_CI_ACTIONS.ACTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiActionsRecord value1(Integer value) {
        setActionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiActionsRecord value2(String value) {
        setActionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjRfcCiActionsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DjRfcCiActionsRecord
     */
    public DjRfcCiActionsRecord() {
        super(DjRfcCiActions.DJ_RFC_CI_ACTIONS);
    }

    /**
     * Create a detached, initialised DjRfcCiActionsRecord
     */
    public DjRfcCiActionsRecord(Integer actionId, String actionName) {
        super(DjRfcCiActions.DJ_RFC_CI_ACTIONS);

        set(0, actionId);
        set(1, actionName);
    }
}
