/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.MdClassAttributes;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdClassAttributesRecord extends UpdatableRecordImpl<MdClassAttributesRecord> implements Record14<Integer, Integer, String, String, Boolean, Boolean, Boolean, Boolean, String, String, String, Timestamp, Timestamp, Boolean> {

    private static final long serialVersionUID = -400761222;

    /**
     * Setter for <code>kloopzcm.md_class_attributes.attribute_id</code>.
     */
    public void setAttributeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.attribute_id</code>.
     */
    public Integer getAttributeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.class_id</code>.
     */
    public void setClassId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.class_id</code>.
     */
    public Integer getClassId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.attribute_name</code>.
     */
    public void setAttributeName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.attribute_name</code>.
     */
    public String getAttributeName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.data_type</code>.
     */
    public void setDataType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.data_type</code>.
     */
    public String getDataType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.is_mandatory</code>.
     */
    public void setIsMandatory(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.is_mandatory</code>.
     */
    public Boolean getIsMandatory() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.is_inheritable</code>.
     */
    public void setIsInheritable(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.is_inheritable</code>.
     */
    public Boolean getIsInheritable() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.is_encrypted</code>.
     */
    public void setIsEncrypted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.is_encrypted</code>.
     */
    public Boolean getIsEncrypted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.force_on_dependent</code>.
     */
    public void setForceOnDependent(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.force_on_dependent</code>.
     */
    public Boolean getForceOnDependent() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.default_value</code>.
     */
    public void setDefaultValue(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.default_value</code>.
     */
    public String getDefaultValue() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.value_format</code>.
     */
    public void setValueFormat(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.value_format</code>.
     */
    public String getValueFormat() {
        return (String) get(9);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.description</code>.
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>kloopzcm.md_class_attributes.is_immutable</code>.
     */
    public void setIsImmutable(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_attributes.is_immutable</code>.
     */
    public Boolean getIsImmutable() {
        return (Boolean) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Integer, String, String, Boolean, Boolean, Boolean, Boolean, String, String, String, Timestamp, Timestamp, Boolean> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Integer, String, String, Boolean, Boolean, Boolean, Boolean, String, String, String, Timestamp, Timestamp, Boolean> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.ATTRIBUTE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.ATTRIBUTE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.DATA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.IS_MANDATORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.IS_INHERITABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.IS_ENCRYPTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.FORCE_ON_DEPENDENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.DEFAULT_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.VALUE_FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return MdClassAttributes.MD_CLASS_ATTRIBUTES.IS_IMMUTABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getAttributeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAttributeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsMandatory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getIsInheritable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getIsEncrypted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getForceOnDependent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDefaultValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getValueFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getIsImmutable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getAttributeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAttributeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsMandatory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getIsInheritable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getIsEncrypted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getForceOnDependent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDefaultValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getValueFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getIsImmutable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value1(Integer value) {
        setAttributeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value2(Integer value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value3(String value) {
        setAttributeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value4(String value) {
        setDataType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value5(Boolean value) {
        setIsMandatory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value6(Boolean value) {
        setIsInheritable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value7(Boolean value) {
        setIsEncrypted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value8(Boolean value) {
        setForceOnDependent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value9(String value) {
        setDefaultValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value10(String value) {
        setValueFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value11(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value12(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value13(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord value14(Boolean value) {
        setIsImmutable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassAttributesRecord values(Integer value1, Integer value2, String value3, String value4, Boolean value5, Boolean value6, Boolean value7, Boolean value8, String value9, String value10, String value11, Timestamp value12, Timestamp value13, Boolean value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdClassAttributesRecord
     */
    public MdClassAttributesRecord() {
        super(MdClassAttributes.MD_CLASS_ATTRIBUTES);
    }

    /**
     * Create a detached, initialised MdClassAttributesRecord
     */
    public MdClassAttributesRecord(Integer attributeId, Integer classId, String attributeName, String dataType, Boolean isMandatory, Boolean isInheritable, Boolean isEncrypted, Boolean forceOnDependent, String defaultValue, String valueFormat, String description, Timestamp created, Timestamp updated, Boolean isImmutable) {
        super(MdClassAttributes.MD_CLASS_ATTRIBUTES);

        set(0, attributeId);
        set(1, classId);
        set(2, attributeName);
        set(3, dataType);
        set(4, isMandatory);
        set(5, isInheritable);
        set(6, isEncrypted);
        set(7, forceOnDependent);
        set(8, defaultValue);
        set(9, valueFormat);
        set(10, description);
        set(11, created);
        set(12, updated);
        set(13, isImmutable);
    }
}
