/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.MdClassActions;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdClassActionsRecord extends UpdatableRecordImpl<MdClassActionsRecord> implements Record8<Integer, Integer, String, Boolean, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 162366107;

    /**
     * Setter for <code>kloopzcm.md_class_actions.action_id</code>.
     */
    public void setActionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_actions.action_id</code>.
     */
    public Integer getActionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kloopzcm.md_class_actions.class_id</code>.
     */
    public void setClassId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_actions.class_id</code>.
     */
    public Integer getClassId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kloopzcm.md_class_actions.action_name</code>.
     */
    public void setActionName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_actions.action_name</code>.
     */
    public String getActionName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kloopzcm.md_class_actions.is_inheritable</code>.
     */
    public void setIsInheritable(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_actions.is_inheritable</code>.
     */
    public Boolean getIsInheritable() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>kloopzcm.md_class_actions.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_actions.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kloopzcm.md_class_actions.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_actions.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>kloopzcm.md_class_actions.updated</code>.
     */
    public void setUpdated(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_actions.updated</code>.
     */
    public Timestamp getUpdated() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>kloopzcm.md_class_actions.arguments</code>.
     */
    public void setArguments(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>kloopzcm.md_class_actions.arguments</code>.
     */
    public String getArguments() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, Boolean, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, Boolean, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdClassActions.MD_CLASS_ACTIONS.ACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MdClassActions.MD_CLASS_ACTIONS.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MdClassActions.MD_CLASS_ACTIONS.ACTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return MdClassActions.MD_CLASS_ACTIONS.IS_INHERITABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MdClassActions.MD_CLASS_ACTIONS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return MdClassActions.MD_CLASS_ACTIONS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return MdClassActions.MD_CLASS_ACTIONS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MdClassActions.MD_CLASS_ACTIONS.ARGUMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsInheritable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getArguments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsInheritable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getArguments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassActionsRecord value1(Integer value) {
        setActionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassActionsRecord value2(Integer value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassActionsRecord value3(String value) {
        setActionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassActionsRecord value4(Boolean value) {
        setIsInheritable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassActionsRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassActionsRecord value6(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassActionsRecord value7(Timestamp value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassActionsRecord value8(String value) {
        setArguments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassActionsRecord values(Integer value1, Integer value2, String value3, Boolean value4, String value5, Timestamp value6, Timestamp value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdClassActionsRecord
     */
    public MdClassActionsRecord() {
        super(MdClassActions.MD_CLASS_ACTIONS);
    }

    /**
     * Create a detached, initialised MdClassActionsRecord
     */
    public MdClassActionsRecord(Integer actionId, Integer classId, String actionName, Boolean isInheritable, String description, Timestamp created, Timestamp updated, String arguments) {
        super(MdClassActions.MD_CLASS_ACTIONS);

        set(0, actionId);
        set(1, classId);
        set(2, actionName);
        set(3, isInheritable);
        set(4, description);
        set(5, created);
        set(6, updated);
        set(7, arguments);
    }
}
