/*
 * This file is generated by jOOQ.
*/
package com.oneops.crawler.jooq.cms.tables.records;


import com.oneops.crawler.jooq.cms.tables.MdClasses;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdClassesRecord extends UpdatableRecordImpl<MdClassesRecord> implements Record11<Integer, String, String, Integer, Boolean, String, String, String, String, Timestamp, Integer> {

    private static final long serialVersionUID = 848102447;

    /**
     * Setter for <code>kloopzcm.md_classes.class_id</code>.
     */
    public void setClassId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.class_id</code>.
     */
    public Integer getClassId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.class_name</code>.
     */
    public void setClassName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.class_name</code>.
     */
    public String getClassName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.short_class_name</code>.
     */
    public void setShortClassName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.short_class_name</code>.
     */
    public String getShortClassName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.super_class_id</code>.
     */
    public void setSuperClassId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.super_class_id</code>.
     */
    public Integer getSuperClassId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.is_namespace</code>.
     */
    public void setIsNamespace(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.is_namespace</code>.
     */
    public Boolean getIsNamespace() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.impl</code>.
     */
    public void setImpl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.impl</code>.
     */
    public String getImpl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.access_level</code>.
     */
    public void setAccessLevel(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.access_level</code>.
     */
    public String getAccessLevel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.description</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.format</code>.
     */
    public void setFormat(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.format</code>.
     */
    public String getFormat() {
        return (String) get(8);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>kloopzcm.md_classes.flags</code>.
     */
    public void setFlags(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>kloopzcm.md_classes.flags</code>.
     */
    public Integer getFlags() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, Integer, Boolean, String, String, String, String, Timestamp, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, Integer, Boolean, String, String, String, String, Timestamp, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdClasses.MD_CLASSES.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MdClasses.MD_CLASSES.CLASS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MdClasses.MD_CLASSES.SHORT_CLASS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MdClasses.MD_CLASSES.SUPER_CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return MdClasses.MD_CLASSES.IS_NAMESPACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MdClasses.MD_CLASSES.IMPL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MdClasses.MD_CLASSES.ACCESS_LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MdClasses.MD_CLASSES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MdClasses.MD_CLASSES.FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return MdClasses.MD_CLASSES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return MdClasses.MD_CLASSES.FLAGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getShortClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSuperClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsNamespace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getImpl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAccessLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getFlags();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getShortClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSuperClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsNamespace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getImpl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAccessLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getFlags();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value1(Integer value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value2(String value) {
        setClassName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value3(String value) {
        setShortClassName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value4(Integer value) {
        setSuperClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value5(Boolean value) {
        setIsNamespace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value6(String value) {
        setImpl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value7(String value) {
        setAccessLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value8(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value9(String value) {
        setFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value10(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord value11(Integer value) {
        setFlags(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdClassesRecord values(Integer value1, String value2, String value3, Integer value4, Boolean value5, String value6, String value7, String value8, String value9, Timestamp value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdClassesRecord
     */
    public MdClassesRecord() {
        super(MdClasses.MD_CLASSES);
    }

    /**
     * Create a detached, initialised MdClassesRecord
     */
    public MdClassesRecord(Integer classId, String className, String shortClassName, Integer superClassId, Boolean isNamespace, String impl, String accessLevel, String description, String format, Timestamp created, Integer flags) {
        super(MdClasses.MD_CLASSES);

        set(0, classId);
        set(1, className);
        set(2, shortClassName);
        set(3, superClassId);
        set(4, isNamespace);
        set(5, impl);
        set(6, accessLevel);
        set(7, description);
        set(8, format);
        set(9, created);
        set(10, flags);
    }
}
