--DROP ROLE activiti;

CREATE ROLE activiti LOGIN
ENCRYPTED PASSWORD 'md529396e43ae92947c301a806c535bb7b9'
NOSUPERUSER INHERIT CREATEDB NOCREATEROLE;

COMMENT ON ROLE activiti IS 'user for workflow engine';

CREATE DATABASE activitidb
  WITH ENCODING='UTF8'
       OWNER=activiti
       CONNECTION LIMIT=-1;


