#!/bin/bash
#this currently always returns 0s as /proc/loadavg is not really supported in cygwin
cat /proc/loadavg | awk '{print "load1="$1";"$2";"$3";0; load5="$1";"$2";"$3";0; load15="$1";"$2";"$3";0;|load1="$1";"$2";"$3";0; load5="$1";"$2";"$3";0; load15="$1";"$2";"$3";0;"}'
